### ISSUE TITLE
[Loopring 3.5] dynamic deposit/withdrawal fees

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1039]
When the gas price is high, the current fixed deposit/withdrawal fees are not flexible. What if we allow the protocol to set the maxWirhdrawalFee instead of withdrawalFee, then during normal time, operator can decide to charge any fee no greater than the max; during jam time, the UI can display a message saying “due to ... we are charging 1.5X withdrawal  fee, do you still want to continue?” This is very much like Uber. Users have the option to continue or quit.

The normal fee will be declared by the operator off chain. The protocol does not care about it.

**Comment by Brechtpd** [comment]
- Changing the onchain fees is just a simple call to `setFees` and the onchain fees are changed so I don't really see how this is fixed and not flexible? Any surplus ETH is also immediately sent back to the user so you could see that as always sending `maxWithdrawalFee` in the tx and only charging `withdrawalFee`. As people have to sign these transactions with MetaMask/... they already have to explicitly confirm they are okay with it.

- Using the Agent + signature method method any fee amount in any token (except ETH) can be collected. The onchain fee doesn't matter as the exchange will pay that and get it back when the request is processed.

- Offchain withdrawal requests are the way to go as they are the cheapest way to do the withdrawal (fees are paid offchain and no request needs to be stored onchain). And these offchain withdrawal requests can also request any fee in any token (including ETH) from the offchain balance.

**Comment by dong77** [comment]
see [[Loopring 3.5] Loopring 3.5 New Features and Changes ](https://github.com/Loopring/protocols/issues/1034)
