### ISSUE TITLE
[Loopring 3.5] Remove offchain cancel feature

### ISSUE THREAD

**Issue by letsgoustc** [Loopring/protocols#1064]
Right now we didn't use offchain cancel circuit in relayer, and nobody complain about it. So I think it's okay to completely remove offchain cancel feature and just let relayer to do soft cancel.

**Comment by dong77** [comment]
see [[Loopring 3.5] Loopring 3.5 New Features and Changes ](https://github.com/Loopring/protocols/issues/1034)
