### ISSUE TITLE
[Protocol3] A better way to encode amount data for on-chain data-availability.

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#108]
The current implementation in 3.0 concatenates all bytes together into a byte array for on-chain data availability. Take the ring settlement data for example, the following fields are to be encoded:

```
- Operator account ID: 3 bytes
- For every ring
    - Ring-matcher account ID: 3 bytes
    - Fee-recipient account ID: 3 bytes
    - Token ID (fee to operator): 2 bytes
    - Fee amount: 12 bytes
    - Margin (paid by first order): 12 bytes
    - For both Orders:
        - Account ID: 3 bytes
        - Wallet account ID: 3 bytes
        - TokenS: 2 bytes
        - TokenF: 2 bytes
        - Order ID: 4 bytes
        - FillS: 12 bytes
        - FillF: 12 bytes
        - WalletSplitPercentage: 1 byte
        - WaiveFeePercentage: 1 byte

```

A total of 112 bytes/ring is required for data, therefore the calldata cost is  (32 + 2 * 40) * 68 = 7616 gas/ring.

**Optimization**: there are certain data representing the amounts of tokens.  Each amount is 12 bytes (can represents 79228162514.3 tokens with 18 decimals), which is pretty wasteful. One way to make them take fewer bytes is to use one byte to represent the number bytes required to actually represent the amount.

For example, 1000 LRC (18 decimals) in binary is: 

```
110110 00110101 11001001 10101101 11000101 11011110 10100000 00000000 00000000
```
it will only take 9 bytes, so we can use totally 10 bytes to represent 1000LRC. Only when the amount is bigger than 309485009.821 (18 decimals) the bytes required is 13, this should be very unlikely.

For 0 amount, one byte will be enough.

There are also ways to make sure those ID fields use as fewer bytes as possible, but that will overcomplicate the encoding/decoding. Given Ethereum will probably lower the gas for data storage, I don't think we need to do much.

**Comment by Brechtpd** [comment]
Done in #156
