### ISSUE TITLE
[Hebao]ConfirmGuardian discussion

### ISSUE THREAD

**Issue by adamchen0510** [Loopring/protocols#1086]
In order of user experience, the confirmGuardianAddition and confirmGuardianRemoval need to be called immediately after user add or remove guardian, but would fail in contract as too early.
Relay can store user behavior and confirm after pendingPeriod passed for the wallet owner, but this would be failed as the signer must be the wallet owner but can not be anyone else.
![image](https://user-images.githubusercontent.com/13066091/79228069-710a1580-7e93-11ea-8934-39bd0bef286a.png)
We need support confirmGuardianAddition and confirmGuardianRemoval called by anyone(especially the relayer), but need to consider if there are some security issues.

**Comment by Brechtpd** [comment]
I think we can allow `confirmGuardianAddition` and  `confirmGuardianRemoval` to be called by anyone. I don't see any security issue with it as I don't think it increases security at all (if the wallet owner keys are compromised than it doesn't matter anyway, and that's the only way an unwanted guardian can be added).

Another option would be to let the wallet owner also immediately sign the confirm transactions so the relayer can do the confirmation when it is possible, but I don't see how this is any better than just allowing anyone to confirm.

**Comment by adamchen0510** [comment]
Yes, just allow confirmGuardianAddition and confirmGuardianRemoval to be called by anyone is better. 
If relay store the signed transaction it mostly will be fail as nonce issue (
if use the nonce increase way, the nonce would be increased if wallet owner do some operation before pendingPeriod passed).
