### ISSUE TITLE
[hebao] Modules at wallet creation not part of the salt used in CREATE2

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#1104]
Because the modules are not a part of the salt the relayer can initialize the wallet with whatever modules he wants. On the other hand, by making it part of the salt it's harder for users to know what data is needed onchain to create their wallet once they already deposited funds to it (now it's just the owner's address).

As this could be a security risk I think we should make the modules part of the salt.

**Comment by dong77** [comment]
should we enforce a sub-ENS domain which should be unique, and use that as the salt? I'm not rallying thinking modules as I need time to refresh my memory about it, it's quite a while since I looked the code last time.

**Comment by dong77** [comment]
or maybe we ask the user to sign a string of his choice `S`, then provide the `hash(sign(S))` as a salt, then later require `sign(S)`for verification?

**Comment by Brechtpd** [comment]
Oh we can already do something similar because when a meta tx is used the wallet owner of the new wallet needs to sign it. 

So I think we can solve the issue by adding `onlyFromMetaTxOrWalletOwner` to `createWallet`. This way the either the wallet owner creates the wallet himself or the complete `createWallet` function call with all parameters is signed by the wallet owner.

**Comment by Brechtpd** [comment]
Fixed in #1106
