### ISSUE TITLE
[LoopringV3.5] Delete label field in Order struct

### ISSUE THREAD

**Issue by kongliangzhong** [Loopring/protocols#1120]
Currently, the label field of Order is not used, and it can be put as a parameter in our API , so maybe we should delete it from the Order structure.

**Comment by Brechtpd** [comment]
Good for me. I guess this also means removing the label elsewhere? Internal transfers and offchain withdrawals currently also have a label.

**Comment by kongliangzhong** [comment]
Yes, I think so.

**Comment by dong77** [comment]
see [[Loopring 3.5] Loopring 3.5 New Features and Changes ](https://github.com/Loopring/protocols/issues/1034)
