### ISSUE TITLE
你们的接口收费吗

### ISSUE THREAD

**Issue by lulei0215** [Loopring/protocols#1190]
准备做个 去中心化的交易所。接入你们的api收费吗？然后 原生支持撮合交易吗

**Comment by dong77** [comment]
接口完全不收费，不过有限流的措施。接口支持交易撮合的。

**Comment by lulei0215** [comment]
app端有源码吗?还是只有web端
质押的 费用大概是多少




| |
lul0215
|
|
lul0215@163.com
|
签名由网易邮箱大师定制
在2020年5月26日 09:14，Daniel Wang<notifications@github.com> 写道：

接口完全不收费，不过有限流的措施。接口支持交易撮合的。

**Comment by dong77** [comment]
后台和产品端代码都不开源。也不需要质押。

**Comment by dong77** [comment]
后台和产品端代码都不开源。
