### ISSUE TITLE
[Loopring 4.0] Allow operator to withdraw funds for users without fees

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1216]
We should allow the operator to sign off-chain withdrawal requests for arbitrary users back to the account owner addresses.

On one hand, this enables the operator to close the exchange without relying on user's actions. On the other hand, this opens a door for the operator to move funds from layer2 to layer1 for other purposes (such as paying back layer1 loans).

**Comment by Brechtpd** [comment]
Can we use onchain withdrawals for this? I'm not really the biggest fan of giving the operator full control over this. This is probably borderline okay for a centralized operator, but I think with a decentralized operator this could be very annoying.

> this enables the operator to close the exchange without relying on user's actions

This is what shutdown mode already allows for, no?

> On the other hand, this opens a door for the operator to move funds from layer2 to layer1 for other purposes (such as paying back layer1 loans).

This could probably be solved with an Agent (or an account contract) that allows the operator to do so, but direct consent with the user. The operator can then decide to offer the service or not depending on the user's decission.

**Comment by dong77** [comment]
> This is what shutdown mode already allows for, no?

Really? I thought users need to do tiger withdrawals with Merkel proof. So if one user does not do that. The operator cannot with this staking immediately.

Let me know if I’m wrong. 
> 在 2020年5月27日，22:09，Brecht Devos <notifications@github.com> 写道：
> 
> This is what shutdown mode already allows for, no?

**Comment by Brechtpd** [comment]
> I thought users need to do tiger withdrawals with Merkel proof. 

This is withdrawal mode. For shutdown mode the exchange owner shuts down the exchange and from then on the only thing the operator is allowed to do is do withdrawals for users (without users needing to authorize this) until all funds are withdrawn to users. Only then can the exchange stake be withdrawn.

**Comment by dong77** [comment]
My bad. I’ll then close this issue.
