### ISSUE TITLE
[Loopring 3.6] use storage for offchain withdrawals

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1238]
This will allow the operator to drop certain requests in the middle of the queue and still be able to use/handle requests with larger nonces from the same user. Otherwise, the relayer will have to invalidate all blocks that contains larger nonces from the same user.

This will cause a small problem in a fully decentralized operator environment. With the current nonce solution (+1 strictly), operator A cannot process a user's request with nonce 3 if he hasn't seen a request from the same user with nonce 2, so he has to hold request with nonce 3. Now he will be more aggressive and will process the request which may invalid a request with nonce2 the user send to operator B. But I think this is a small problem as most users will not use two operators simutanously.

**Comment by Brechtpd** [comment]
So we want this even if all requests that modify the nonce are handled by the same circuit?

I'm not totally completely sure when this can happen if we provide instant apparent finality. Transactions that use nonces are executed immediately after the tx is signed by the user, no? (as in the internal relayer state is modified and the tx is added to a block) How can a tx suddenly become invalid after the user signed a different tx? Doesn't this mean it was once valid and added to a block, but then removed for some reason and the state changes it caused are reverted in the internal state?

**Comment by dong77** [comment]
Hmm.. I auctually don't have a strong preference. I think +n will probably offer the relayer some flexibility, but I cannot convince myself that reason is strong enough.

**Comment by dong77** [comment]
After talking to @hosschao and @lydy, the relayer team will drop this feature request.

**Comment by hosschao** [comment]
Hi brecht, we hope removing nonce for withdraw request. (use storage id) So that we have ability to fail some user's offchain requests. (Or user may want to cancel that.) Is it easy to achieve that?

**Comment by dong77** [comment]
I like this idea as it will give relayer more flexibility to handle withdrawals of large values first...

**Comment by dong77** [comment]
@hosschao I talked about this request with Brecht and it seems we can do it. Brecht will figure out whether there is an impact on the size of DA.
