### ISSUE TITLE
[Loopring 3.6] Remove native ETH support

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1270]
Maybe we should remove the native support for Ether and by wrapping and unwrapping ETH to/from WETH as part of the layer1 deposit/withdrawal operations. This will simplify the core codebase.

**Comment by Brechtpd** [comment]
Could make sense. This wrapping/unwrapping functionality could also be useful for things like tighter integration with other tokens like renBTC. I think most things can already be done in the deposit contract/an agent contract, but perhaps it can be done cleaner or better in some other way.

**Comment by dong77** [comment]
@Brechtpd It seems we decided not to do this. The reason is that ETH transfers are cheaper than WETH, is it?

**Comment by Brechtpd** [comment]
Yes. And it's still possible to do this in the deposit contract if we ever need it. We could even allow he user to choose by making use of the deposit auxiliary data where we could only wrap/unwrap when requested.
