### ISSUE TITLE
[Protocol3.6] emit an event when withdrawFromApprovedWithdrawal succeeded

### ISSUE THREAD

**Issue by kongliangzhong** [Loopring/protocols#1276]
Feedback from relay team.

**Comment by Brechtpd** [comment]
I think in all versions this logs a `WithdrawalCompleted` event, even in 3.1:
https://github.com/Loopring/protocols/blob/a7a8b3e2b4b6f07405389ca2f5197ae91b48d733/packages/loopring_v3/contracts/impl/libexchange/ExchangeWithdrawals.sol#L515`

**Comment by kongliangzhong** [comment]
Ok, I see. thanks.
