### ISSUE TITLE
[Loopring 3.6] Remove Maintenance mode

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#1280]
I think it's best to remove this mode and handle this in an operator contract. For example, just let anyone submit blocks to process withdrawals after inactivity like Vitalik proposed.

It's also more difficult/expensive to check what a block actually does in 3.6 so we'd probably have to change some rules around this as well. But just opening up to let other people jump in (maybe incentivised in some way) would be better any way because it doesn't completely stop the contract so other parties can still depend on it.

This can all be handled in an operator contract so we don't have to figure out how exactly we'd want this to work.

**Comment by dong77** [comment]
I can imagine how to switch on the access for other operators, but when/if we can turn off the access and take back the control after the relayer becomes ready again.

**Comment by Brechtpd** [comment]
> I can imagine how to switch on the access for other operators, but when/if we can turn off the access and take back the control after the relayer becomes ready again.

I think there's several ways to do that. We could open it up for a limited set of time, let's say 12 hours, before turning control back to the original operator for a short period of time, let's say 1 hour. If the operator still doesn't do anything we open it back up. And this could repeat as long as necessary. The idea here is that the main operator also wants this to happen, otherwise he would do it himself. So there could even be some manual call on the operator contract so that the main operator could release control or take back control when he wants (and is able to do so).

> The maintain mode also disables all onchain requests, this is part of the core protocol logic, so I don't know how the protocol handles this without the knowledge of such a mode.

The idea would be that onchain requests would still be processed by the other operators so people can still get their money out even if the main operator if offline. So not closing the onchain requests is actually something we want, that's what makes it better than our current maintenance mode where basically everything stops for some unknown time, which of course isn't a great user experience.

Why operators show up when this happens could be for a number of reasons. Other services that depend on it may do it to keep their users happy. We could also use the exchange stake to pay these temporary operators some extra money for each withdrawal they process for users. Etc...
