### ISSUE TITLE
[Hebao_v1] 内部测试checklist（主网）

### ISSUE THREAD

**Issue by kongliangzhong** [Loopring/protocols#1314]
### Guardian
- [x] 添加第一个guardian，应该能立刻生效
- [x] 添加第二个guardian，应该能立刻生效
- [x] 添加第三个guardian，应该会处于pendingAdd状态，24小时后生效
- [x] 删除pendingAdd状态的guardian，能立刻生效
- [x] 删除生效的guardian，应该会变成pendingDelete状态
- [x] 撤销guardian的删除（处于pendingDelete状态的guardian）

### Lock
- [x] 当guardian数目 < 2 时，不能Lock
- [x] 当guardian数目 >= 2时，可以Lock（需要guardian签名）
- [x] Lock的钱包，可以通过Guardian Unlock
- [x] Lock的钱包，24小时后自动解锁
- [x] Lock状态下，做修改每日限额，添加删除白名单地址的操作

### Recover
- [x] 当guardian数目 < 2 时，不能Recover
- [x] 当guardian数目 >= 2时，可以Recover（需要多数guardian签名）
- [ ] recover后，钱包的Lock自动移除
- [ ] ~~recover后，如果新的owner是guardian，自动移除该guardian~~

### Whitelist
- [x] wallet owner可以添加地址到whitelist，生效时间为24小时后
- [x] 如果有wallet owner和多数guardian的签名，可以立刻添加地址到whitelist
- [x] wallet owner可以删除whitelist中的地址，立刻生效

### QuotaTransfers
- [x] wallet默认的qouta数目为10ETH，owner可以修改quota，24小时后生效
- [x] 如果有wallet owner和多数guardian的签名，可以修改quota并立刻生效
- [x] 转账ETH会减少quota，24小时后恢复
- [x] 转账或者approve任何在priceOracle中有价格的token，都会按照价格减少quota
- [x] 调用合约，需要消耗ETH或者要做token 的approve，会按照价格减少quota
- [x] 向白名单中的地址转账(ETH or token)或者approve，quota不减少
- [x] 调用在白名单中的合约，不会减少quota
- [x] 不能调用在priceOracle中有价格的token合约

### ApprovedTransfers
- [x] 如果有wallet owner和多数guardian的签签名，可以超额转账或者approve，不计入quota
- [x] 如果有wallet owner和多数guardian的签签名，调用其他合约发生的费用不受quota限制，不计入quota

### DappTransfers
- [x] 在DappStore中的地址，owner的转账和approve不受quota限制，并且不计入quota
- [x] 当前支持的Dapp有Loopring Exchange和Loopring Staking合约

### 创建钱包
- [x] 创建钱包流程正确
- [x] 创建钱包进入app后弹出对话框进入排队页面完成任务创建钱包
- [x] 创建钱包需要邀请码，并且可以充值LRC进入排队免费钱包、或者付费LRC立即创建钱包
- [x] 钱包创建成功后自动注册ENS
- [x] 钱包创建成功后自动创建DEX账号
- [x] 钱包创建成功后自动添加官方Guardian

### 恢复钱包
- [x] 小于两个Guardian无法恢复钱包
- [x] 恢复钱包需要n/2+1个人审批（官方自动审批）

### 检查版本信息
- [x] 检查版本号和发布一致，在设置->关于中查看

### 升级
- [x] 正常下载并安装

### 钱包界面
- [x] 用户金额显示无误
- [x] 转账记录显示无误

### Guardian操作
- [x] 能正常添加钱包Guardian、官方Guardian、硬件Guardian
- [x] 添加钱包Guardian需要对方同意，对方也可以拒绝
- [x] 可以取消添加Guardian、删除Guardian、取消删除Guardian等操作
- [x] 添加Guardian需要等链上完成，链上未完成不可继续操作
- [x] 可以添加对方到白名单（add trust，主网24小时生效）、移除出白名单（立即生效）
- [x] 可以对Protects操作Lock（protects需要两个guardian才可以lock）或者unlock
- [x] 可以修改Guardian的名字

### 联系人
- [x] 可以在联系人列表添加联系人
- [ ] 当联系人仅为联系人时（不是Guardian），可以删除联系人
- [x] 可以重新命名联系人
- [ ] 连续发送信任，不信任，信任，看看状态现实是否正确

### 设置日限额和转账
- [x] 可以设置日限额，默认一天是10ETH的额度
- [x] 设置日限额主网24小时后生效
- [ ] 合约内能拿到有price的token会占用日限额
- [x] 转账给trust列表内的用户不消耗日限额
- [x] 超额转账需要guardian审批，没有guardian的时候是自己签名自己审批。所以没有guardian的时候验下邮箱后就可以超额转账

### 操作付费
- [ ] 有的操作需要付费，现在暂定除了开户（可选付费）、dex开户、add 3个gardian、recover一次免费外，其他都要收费
- [x] 可以在设置->费用列表查看扣费币种列表，并调整扣费顺序
- [ ] 确认扣费顺序无误、扣费金额无误

### 更改、重设密码
- [x] 用户可以更改密码，到安全->安全设置更改，验证老密码即可更改
- [x] 用户可以重设密码，在登录界面忘记密码可以进行更改，验证邮箱即可更改
- [x] 更改或者重设完密码可以正常操作，登录app、添加guardian、设置日限额、dex交易等操作

### 用户操作记录
- [x] 可以在设置->操作记录查看用户所有的操作记录
- [x] 可以guardian页面查看针对guardian的操作记录
- [x] 操作记录正常

### Dex操作
- [x] 能正常开户、重设账户（recover后）
- [ ] 能正常充值、提现ETH、LRC等，并且能够正确显示提现冻结金额
- [x] 开户成功后能支持交易，下单、取消订单，并且能够正确显示下单冻结金额
- [x] Loopring Pay可以正常工作

**Comment by dong77** [comment]
moved to https://github.com/Loopring/protocols/wiki/App_Testing_Checklist
