### ISSUE TITLE
[Protocol3] Same circuit with/without data-availability

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#139]
Currently we will use different circuits, but it's possible to re-use the data-availability circuit, which is a bit more expensive (~10%) because it needs to hash the data-availability data. Once we have optimized the data-availability data the performance difference may not be significant any more. 

It would work like this. Instead of hashing all calldata at once, we hash the data that's actually needed on-chain and the data-availability data separately. Both hashes are then hashed together to create the single public input for the circuit. This allows an exchange that doesn't want to use data-availability to send just the hash on-chain. Exchanges that want to use data-availability will still send all the data and the hash is still calculated on-chain. The exchange contract simply also has a `commitBlock` function that takes the data-availability as a hash directly.

This may also be useful to reduce the cost of sending all this data from the Operator contract to the Exchange contract (not sure how expensive this is). It's up to the Operator contract anyway to ensure that the data-availability data can easily be extracted from the Ethereum block data.

**Comment by dong77** [comment]
@Brechtpd This is done on the protocol level, isn't it?

**Comment by Brechtpd** [comment]
Yes, it changes the input value of the circuit because the hash is calculated differently in the Exchange contract.

**Comment by Brechtpd** [comment]
If the circuits get more efficient by using a cheaper hash function for the Merkle tree it can still make sense to use a different circuit without DA if it's still significantly cheaper (the DA data needs to be hashed using sha256 which is still expensive in circuit). Currently the difference is only 5%.

The same circuit can be used with and without onchain DA as follows:

```
function commitBlockWithDA(
  bytes memory data,
  bytes memory dataAvailabilityData)
{
  // The operator passes in the DA data and we hash it onchain, ensuring the DA is onchain
  bytes32 dataAvailabilityDataHash = sha256(dataAvailabilityData);
  commitBlockInternal(data, dataAvailabilityDataHash)
}

function commitBlockWithoutDA(
  bytes memory data,
  bytes32 dataAvailabilityDataHash)
{
  // The operator passes in the DA hash directly, the DA is not guaranteed to be onchain
  require(!S.onchainDataAvailability, "ONCHAIN_DA_CANNOT_BE_ENABLED");
  commitBlockInternal(data, dataAvailabilityDataHash)
}

function commitBlockInternal(
  bytes memory data,
  bytes32 dataAvailabilityDataHash)
{
  bytes32 dataHash = sha256(data);
  bytes32 publicDataHash = sha256(dataHash, dataAvailabilityDataHash);

  // publicDataHash is used as input for the verifier of the circuit WITH DA
}
```

But that doesn't stop us from still supporting a circuit that doesn't hash the DA like we currently do if we want to:

```
function commitBlockCircuitWithoutDA(
  bytes memory data,
  bytes memory dataAvailabilityData
  )
{
  // dataAvailabilityData is not used, the circuit only hashes 'data'
  bytes32 publicDataHash = sha256(data);
  // publicDataHash is used as input for the verifier of the circuit WITHOUT DA
}

```

Depending on the throughput/trusted setups/... it may or may not be worth it to support the circuit that lacks DA support.

**Comment by dong77** [comment]
@Brechtpd maybe we can close this issue, as in our current implementation, we clearly use two separate set of circuits. What do you think?

**Comment by Brechtpd** [comment]
I'm okay with closing this. The split between the data needed onchain and the DA data can still be useful, but if so another issue can be created (with a more appropriate name).

The only reason we use a different circuit is because it currently uses 10,000 constraints to hash the DA data in the circuit, which is about 15% of the cost/trade.

I think no DA will be getting less and less important. We'll be able to do ~1000 trades/second with DA in Istanbul at 16 gas/ non-zero byte. It seems likely the cost will be decreased even further in HFs after Istanbul (and ETH 2.0).

So we can just leave everything as it is, I think the chances are pretty low that we'll actually use the versions without DA.

**Comment by dong77** [comment]
I'm on the same page - we prefer turning on the onchain data availability to guarantee DEX security. I'm closing this issue.
