### ISSUE TITLE
[Protocol3] Add circuit to do a token transfer between accounts

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#148]
This would be easy to add, and would allow using our protocol for general payments. Could also be useful for people that trade using multiple accounts to transfer token between those accounts.

**Comment by dong77** [comment]
@Brechtpd I think this is done on the protocol level, isn't ?

**Comment by Brechtpd** [comment]
@dong77 No, smart contracts/test code do not know of offchain transfers yet. The [circuit code for this](https://github.com/Loopring/lightcone2/pull/111) isn't merged yet and still needs some modifications (like floating point data for DA).

**Comment by dong77** [comment]
@letsgoustc can you document which branch we used to keep all the related work?

@Brechtpd do you think the implementation is complete?

We can merge the Transfer logics to master once we have https://github.com/Loopring/protocols/issues/473 implemented.

**Comment by Brechtpd** [comment]
Pretty much done yes. There are some minor comments I did on the PRs which were not yet done but should be easy to do. I could do them if the others are busy with other things.

It may make sense to reuse this circuit for the fast-withdrawals (+more) if that ends up making sense, but I don't think we have to decide that now or implement it in this PR if we even decide to do that.

**Comment by dong77** [comment]
If you can easily fix any potential issues without too much involvement, please go ahead. Adam and Yue are working on an internal market making tool.

**Comment by Brechtpd** [comment]
Implemented in #409
