### ISSUE TITLE
[Loopring 3.6] reoragnize contract code into `core` and `aux`

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1481]
As we are extracting logic from the core protocol into customizable contracts, such as IDepositContract, IAgentRegistry, etc. We should really keeping only the core logics into its own directory `core` and more other non-core contracts into an `aux` directory. The aux directory should contains:
- ownership/operator/access related contracts
- customized deposit contracts
- price feed/sellers
- protocol fee vault
- compressors

So eventually we should have:

- core/iface
- core/impl
- staking
- aux
- lib
- thirdparty

**Comment by Brechtpd** [comment]
Good idea. Let's do that when all open PRs we have now are merged in the protocol-36 branch, otherwise merging will probably be hard.

**Comment by dong77** [comment]
@Brechtpd Lets get this done so that we can resume conversations with auditors to get a new quote.

**Comment by Brechtpd** [comment]
Will do this today.

**Comment by dong77** [comment]
Done
