### ISSUE TITLE
[Loopring_3.6] code review optimize customData in Transfers

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1506]
Maybe we should remove "customData" from the transfer to save DA.

**Comment by Brechtpd** [comment]
It's there because otherwise we need to pad with zeros anyway, so I thought way not make it possible to use those bytes in some useful way. If it's not used they are zeros as well, so it's effectively the same as padding so doesn't increase costs in any way. :)

**Comment by dong77** [comment]
Can we add a comment in the code?
