### ISSUE TITLE
[Loopring_3.6] protocol-fee payment account

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1508]
Brecht, I remember in 3.1 the operator needs to increase his nonce and sign the block using his EdDSA key. Is it still the case in 3.6?

As I recall, the operator has to have an account to pay the protocol fee, that's why he needs to sign, but this "operator account" can actually be any account, and can change from block to block.  Correct?

**Comment by Brechtpd** [comment]
> Brecht, I remember in 3.1 the operator needs to increase his nonce and sign the block using his EdDSA key. Is it still the case in 3.6?

Yes.

> As I recall, the operator has to have an account to pay the protocol fee, that's why he needs to sign, but this "operator account" can actually be any account, and can change from block to block. Correct?

That's right.
