### ISSUE TITLE
[Loopring_3.*] Allow flash loans on our deposit contract

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#1510]
Could be free of charge to ourselves, and/or we could charge a fee so anyone can use it. This fee could even be used as top pay LRC stakers.

**Comment by dong77** [comment]
For the purpose of discussion, can you provide an example use case?

**Comment by Brechtpd** [comment]
Decent article comparing other projects offering this: https://defiprime.com/flahloans-comparison

Aave/Uniswap charge a fee for flash-loans, dYdX does not. So if a token is not available on dYdX and we want to use a flash-loan it would be more expensive than compared to what we can do ourselves.

For ourselves, bringing L1 liquidity into L2, doing something like this: https://github.com/Loopring/protocols/issues/1196#issuecomment-633324180

The above is to make the swap instantaneously and seamlessly integrate it in order books, though that isn't really necessary if we want to reduce risks. It doesn't really need to be instantaneously (which wouldn't be the case on L1 either) so we can batch these swaps for some time and then try to fulfil them (within some allowed slippage, which we can do with our orders) on L1 using a flash-loan. If the price changed too much the swaps done on L2 may be insufficient to pay back the flash-loan, in which case the block won't be submitted and the operator can try again at higher prices (but the operator can charge a bit extra so there's less of chance of this happening).

The same mechanism can be used to interact with other L1 smart contracts like compound/Aave/... which return some other token and essentially allows us to batch many transactions in a way that only needs a single L1 interaction with that target smart contract, making it much cheaper and there's no need for any direct liquidity on L2. Though in some cases I guess it would also be possible to make some initial liquidity available on L2 and replenish when needed. So if a user wants compound tokens they would just do a trade to get them against what's available in the books, but of course this is limited by the amount of liquidity there and doesn't work well in some cases probably.

Other people may also just want to use the flash-loan functionality we offer, and it seems like we could even charge a fee for that, so potentially an easy and secure way to earn money on the funds stored in the exchange.

**Comment by dong77** [comment]
" earn money on the funds stored in the exchange." I get the point. I was thinking hard in another direction, how flashloan can be used inside our rollup, completely missing the point.

I guess it's correct to say we can offer flashloan in an IDepositContract implementaiton.

**Comment by dong77** [comment]
I understand if we add flashloan feature to our IDepositContract implementation, the ether/tokens in the contract can be used to earn money without any risks. The part I don't understand is how our rollup benefits from that, or the L1-L2 interaction part. Lets talk about it over the phone.
