### ISSUE TITLE
[Loopring_3.6] Remove AccountTransferTransaction completely

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1523]
Brecht, based on our conversation last night, I propose to remove the AccountTransferTransaction completely, here is why:

- It's a nice-to-have feature and we don't really have the bandwidth to develop a stateless wallet app within 1 year. Actually we don't have a plan at all. 
- If we have more bandwidth, we may want to spend time on more future-proof technologies, such as layer-2 contract-based smart wallet that can provide more functionalities and extensibility.

Having this tx type will only complicate our codebase and increase audit cost, so lets drop it - **actually I recommend we delete it completely together with AccountNEW which is only disabled, not removed.** I don't think we'll come back to use the same tech-stack to re-enable these features at all.

**Comment by Brechtpd** [comment]
Makes a lot of sense, will do.
