### ISSUE TITLE
[Loopring 3.6] Support 2**24 (more than 16 million) number of tokens.

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1545]
I suggest to make the following changes in order to support 2**24 number of tokens:

- Allow operator to withdraw for users without user authorization. This is currently only possible in shutdown mode.
- Move the mapping between the tokenID and the token information (token address, ERC1155 token ID, etc) to IDepositContract. and inside the core protocol, the only information we know about a token is its unique protocol-wise ID, nothing else.
- We use the same ideas as 'order raising', and allow tokenID to take the balance leaf at position `tokenID % 2**6`. When we deposit/withdraw from a token, we check the current tokenID value inside the BalanceLeaf must equal to the token we try to depsit/withdraw. We also only allow tokenID to grow by `2**6` for each BalanceLeaf. For deposits, if the new tokenID is greater than the current value in the BalanceLeaf, the current balance must be 0.
- Use uint24 as tokenID type

**Comment by Brechtpd** [comment]
Most of this I think already discussed in #1255 

There's a couple of ways to do this, just making the tree larger of course the easiest. :) If 2**16 - 2**20 tokens is enough (which should be the case) than that'll only cost us 8,000 - 16,000 constraints, which may be worth it to keep things simple (and the same as things are now). Having spoken with some NFT projects they are always talking about a couple of thousands of different NFTs they have, so I don't see a lot of issues there.

**Comment by dong77** [comment]
2**16 should be enough.
