### ISSUE TITLE
Change feebips in transfer/withdraw(off-chain) to max-feebips

### ISSUE THREAD

**Issue by hosschao** [Loopring/protocols#1688]
Just like what we did in order request. Max feebips makes an opportunity for relayer to decided exactly feebips based on some infos (like VIP level).

**Comment by dong77** [comment]
Brecht is working on changing the withdrawal fee as the max fee a user would like to pay, the actual fee will be determined by the relayer.

There may be future use cases to change the transfer to also have a max fee and allow a discount by the relayer. But I don't know what's the extra cost on-chain, and whether it will make all transactions more expensive.

**Comment by dong77** [comment]
So for EdDSA signed offchain transfers and withdrawals, we know support maxFee (meaning fee <= maxFee), and for transfers and withdrawals authorized in other means, we will always use maxFee (does the relayer need to provide a fee value but it's just not used?)

**Comment by Brechtpd** [comment]
When not using an EdDSA signature the relayer can fill in any `maxFee`, but that's okay because the user needs to sign/approve the actual fee amount. So the relayer can fill in any `maxFee >= fee` so the circuit is valid, but it has no real impact.

**Comment by dong77** [comment]
> When not using an EdDSA signature the relayer can fill in any `maxFee`, but that's okay because the user needs to sign/approve the actual fee amount. So the relayer can fill in any `maxFee >= fee` so the circuit is valid, but it has no real impact.

Haha, I see the point.
