### ISSUE TITLE
[Help wanted] How to prevent exchanges behave maliciously in order-matching？

### ISSUE THREAD

**Issue by timfaner** [Loopring/protocols#1798]
Is there anyway to prevent exchanges behave maliciously in the order-matching phase in loopring v3？
Say a adversary controls an exchanges‘ server and makes orders match randomly, then submit the blocks to ETH chain.  Is there any scheme to prevent such attacks in loopring protocol?

**Comment by dong77** [comment]
It's very hard, if not impossible, to decentralize the relayer while keeping the same offering of high throughput and immediate finality. Users can use limit price orders to make sure their orders are filled correctly in the worst cases. In the future, users can opt-out based on the quality of service offered by different relayers. Out-of-order matching of orders is an important part of the QoS, if a relayer is doing evil, it will lose users as all funds can be easily transferred away from that exchange, and **the exchange can do nothing to prevent user withdrawals** this is the part Loopring protocol guarantees. In other words, Loopring doesn't guarantee exchange QoS, but assures user's funds are secured and withdrawable under all circumstances.
