### ISSUE TITLE
[Loopring AMM] AgentRegistry

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#1824]
Currently the owner can immediately unregister an agent and immediately unregister all universal agents. This is currently a problem because the pool contract currently depends on being an agent of people interacting with the pool. This could also effect other functionality we may build in agents (though things that don't impact block creation like fast withdrawals are much less effected by this, in the worst scenario someone could just waste some gas doing an operation that isn't allowed).

Easiest solution: all pools are whitelisted and we don't allow people to disable whitelisted agents. I think this is fine.

Of course more complicated methods with time delays are also possible, but I'm assuming that's not worth it for the added relayer complexity.

**Comment by dong77** [comment]
I think this easiest solution should be fine. I created this PR: https://github.com/Loopring/protocols/pull/1834
