### ISSUE TITLE
[Loopring 3.6] Bug in AccountUpdate regarding fee and maxFee

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1847]
In our smart contract, there is only this "fee" field in AccountUpdateTransaction. It is supposed to be interpreted as the max fee the user would like to pay. In the circuit 'AccountUpdateCircuit', there is  `fee` and `maxFee` fields, but at the end of the file, we pushed the actual fee we charged onchain as part of DA. this makes the tx hash different and failures of signature verification.

```cpp

    const VariableArrayT getPublicData() const
    {
        return flattenReverse(
          {type.bits,
           owner.bits,
           accountID.bits,
           feeTokenID.bits,
           fFee.bits(),
           compressPublicKey.result(),
           nonce.bits});
    }
```

**Comment by dong77** [comment]
The same issue exists for Tranfers and Withdrawals as well.

**Comment by dong77** [comment]
I suggest that we change "fee" to "maxFee" in contracts so users will notice the nuance when signing the transactions.

**Comment by Brechtpd** [comment]
Explained in https://github.com/Loopring/protocols/issues/1688#issuecomment-686481044 and https://github.com/Loopring/protocols/pull/1689.

We always need at least the actual fee being paid in the DA, because that's the one needed for reconstructing the Merkle tree.

**Comment by Brechtpd** [comment]
It's actually pretty easy to support maxFee, we just put it in the auxiliary data for those transactions, which we already use for `validUntil`. Circuits remain the same.

**Comment by dong77** [comment]
I understand that. Is it possible that we put `maxFee`s in `auxiliaryData` before we calculate transaction hashes in the smart contracts?

**Comment by Brechtpd** [comment]
Yep https://github.com/Loopring/protocols/issues/1847#issuecomment-705600453

**Comment by dong77** [comment]
Great, could you please make that change so the new relayer can make the according changes shortly?

**Comment by Brechtpd** [comment]
Okay, will do this today.

**Comment by dong77** [comment]
@Brechtpd in the current implementation, we keep the `maxFee` value in the transactions auxiliary data. Do you think we should use something called `maxFeeDiff` (= maxFee - fee) so we have a bigger chance of having zeros in calldata?

**Comment by dong77** [comment]
<img width="730" alt="Screen Shot 2020-10-09 at 10 47 16" src="https://user-images.githubusercontent.com/1710087/95536153-d2630980-0a1c-11eb-955c-7155217a7033.png">

Also in side aux data, should the maxFee be decoded as a float:

```solidity
accountUpdate.maxFee = uint(auxData.maxFee).decodeFloat(16);
```
