### ISSUE TITLE
[hebao 1.2] addGuardian should support txAwareHash

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1921]
As of now, the wallet to be added as a guardian must approve being added as a guardian. If the wallet transacts before such approval, the pending addGuardian tx will fail.

**Comment by Brechtpd** [comment]
> As of now, the wallet to be added as a guardian must approve being added as a guardian.

Is that the case?

**Comment by dong77** [comment]
Yes, but we figured out another design to get rid of the approval. This feature is no longer required.
