### ISSUE TITLE
[Protocol3] Batched proof verification

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#200]
Large circuits need a lot of memory. If we can use smaller circuits and efficiently do batched proof submission than that will lower the proof generation cost while the throughput remains roughly the same. Not sure what the limit of the circuit size is for this to be possible.

Links: 
- https://github.com/matter-labs/Groth16BatchVerifier
- https://ethresear.ch/t/batching-of-zk-snark-proofs/5626

**Comment by dong77** [comment]
We need a new branch to catch all related implementation in case this is eventually not what we wanted.

**Comment by Brechtpd** [comment]
Done in #283
