### ISSUE TITLE
[Protocol3] Allow withdrawing exchange balance not owned by users

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#201]
The exchange contract can be sent tokens not deposited by users e.g. air drops, token swaps, user error, ... These funds should be withdrawable, most likely by the exchange owner.

We can do this by keeping track of what balance is actually owned by the users. The part that can we withdrawn is `token.balanceOf(exchange) - (totalDeposited[token] - totalWithdrawn[token])`.

**Comment by dong77** [comment]
We need to disable the default function.
