### ISSUE TITLE
[Protocol3] Skip expensive token withdrawals while distributing

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#202]
Both ETH transfers as well as ERC-20 token transfers can cost a lot of gas. This can be used as an attack because the withdrawals need to be automatically distributed by the operator. Withdrawals that are more expensive than expected need to be skipped while the operator is distributing. The user can always manually withdraw without any gas limit.

For ETH we currently use `address.transfer` which has a 2300 gas limit and throws if more gas is used. We need to do it in a way that doesn't throw but simply returns true/false so we can skip it.

For ERC-20 we need to set a gas limit on the token transfer.

**Comment by dong77** [comment]
#211
