### ISSUE TITLE
[Protocol3] Better maintenance mode implementation [including tests]

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#206]
The current implementation lacks some flexibility. If the operator purchased some down time, he has to wait for all time to be used before the DEX can restore to the normal mode. 

We should enable the DEX operator to exit the maintenance mode whenever they want, and all unused downtime can be used in the future. The cost per unit of downtime should be a parameter at the protocol level. 

The unit of the downtime should be probably a minute instead of a second.

**Comment by Brechtpd** [comment]
Done In #212
