### ISSUE TITLE
[Android] [WalletConnect] Failed to interact with Curve.finance and Uniswap with L1 account

### ISSUE THREAD

**Issue by wjw12** [Loopring/protocols#2073]
I tried to supply my WBTC in L1 account to Curve protocol using WalletConnect but the transactions failed. It caused me to lose 0.05 WBTC which doesn't seem recoverable. After this incident I did another two experiments with Curve LP deposit and Uniswap  trading. Met similar failures. Here are the details.
1. I logged in Curve RenBTC pool (https://www.curve.fi/ren/deposit) with WalletConnect of Loopring wallet. I wanted to deposit 0.05 WBTC to the pool. The deposit setting is as below
![image](https://user-images.githubusercontent.com/8369203/101119407-2236fa80-35a0-11eb-8002-1f87d7241ea3.png)

After entering the amount of WBTC and clicking "deposit" on Curve website, I was prompted to confirm a transaction on the mobile wallet. I confirmed the transaction, waited for several minutes, finally two transactions poped up on the device:
![image](https://user-images.githubusercontent.com/8369203/101100162-e178ba80-357a-11eb-8695-5ecce023f313.png)
The first (former) one is a successful transfer of 0.05 WBTC to a Curve contract. Tx id: https://etherscan.io/tx/0x19149e554fca33a929325b73fb830b3111f94b8c8ff16a600f5ba7391f7f488f
The other one (appeared as "Contract Call") failed. Tx id: https://etherscan.io/tx/0x1bb1a5488b8f90bb6bfde73c9b5e88e6e9da338b12d9b4eea1dd3ef110a7149f

After that, my WBTC balance was deducted 0.05 but I did not receive any Curve LP tokens.
Please look into these two transactions and let me know if there is a way to recover my funds.

2. I tried again with Curve USDT pool (https://www.curve.fi/usdt/deposit) I tried to deposit 0.001 USDT to the pool for LP. The setting is
![image](https://user-images.githubusercontent.com/8369203/101119576-780ba280-35a0-11eb-841a-561277322082.png)
Clicked "deposit". Confirmed one transaction on mobile device. Finally two transactions showed up:

First, the only successful one: it sent 0.001 USDT to uniswap contract address https://etherscan.io/tx/0x50851c397e7ca7a56e0d8c26a2eb365bd9f1da5218ed022b4ef07a5d95feeb2a

Second, a failed contract https://etherscan.io/tx/0xf1b1b92bd3d1bfe15384cbda9a73c45654c715588a410e7103fd604f4d3e3f3d

As a result of two transactions (although I only confirmed once!) I transfered 0.001 USDT to a Curve contract, but received no LP tokens.

3. I decided to try again with Uniswap. This time I tried to swap USDT on my L1 account for DAI. So I logged in Uniswap with WalletConnect, found the swapping page on the website, set the input and output tokens. I entered the amount 0.001 USDT that I wanted to swap from. The first step was to approve spending of USDT, so I clicked yes on the website. Mobile app prompted me to confirm the transaction. I confirmed. The transaction failed.

Tx id is https://etherscan.io/tx/0x6154ec58a3d8ae587e7f50c6d0ad60a0cd7c0f2816d32cb2a21144f90ef2f17f

This transaction was reverted. No token was lost.

It seems that L1 account cannot interact with external contracts which involves token transfers. I'd really appreciate it if you could help recover my loss of funds. I'd be glad to provide more details if necessary. Btw I'm a native Chinese speaker so if you find it convenient I can communicate with your dev team in China.

More info that might be helpful:
My device is Google Pixel 3
OS version: Android 11
My wallet address: swimsmoke.loopring.eth

**Comment by dong77** [comment]
This is a known issue. We are working on WalletConnect support.

**Comment by dong77** [comment]
This issue should have been fixed, @wjw12
