### ISSUE TITLE
[Protocol3] Fine-tune downtime price

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#213]
Previous discussion: #212

Currently every exchange pays a fixed price for downtime:

```
cost = durationMinutes.mul(S.loopring.downtimePriceLRCPerMinute());
```

Maintenance mode locks out the ability of users to withdraw, so it' extremely important that the time in maintenance is as short as possible.

So in any case the price for downtime needs to be high in all cases. I think it should make sense to make it more cost effective for exchanges to have backup servers to handle a limited number of on-chain requests than to buy maintenance mode. Maintenance mode should mainly be used for unforeseen problems because it greatly impacts user experience.

We can change the downtime price by
- checking totalDowntime / totalExchangeLifetime and making it more expensive the more the exchange has been in maintenance
- checking how much funds are locked into the Exchange
- ...

If we implement this, it probably makes sense to implement any additional logic for this in the Loopring contract instead of the Exchange contract.

**Comment by dong77** [comment]
@kongliangzhong, I'm assigning this issue to you so you can work on this one and https://github.com/Loopring/protocols/pull/349 and #350 all together **before** the release of beta3.

**Comment by dong77** [comment]
Completed in #343
