### ISSUE TITLE
'Deposit to activate layer-2' still shows up after I already deposited

### ISSUE THREAD

**Issue by avalyn2** [Loopring/protocols#2222]
already paid  0.00488059 Ether ($9.60)  -transaction logged in etherscan- to transact 1nch on Loopring

`Approved1INCHFor Trade OnLoopring: Exchange v2 Deposit`

but I am still getting the 'deposit to activate layer-2' message on Loopring? Why is this? thanks

**Comment by dong77** [comment]
For each token, you need to do one ERC20 approval, then later you can do deposits. This rule apply to almost all DeFi projects. The Approval is not a token transfer but to authorize a contract to transfer tokens for you.
