### ISSUE TITLE
Loopring 3.6: Apply a constant factor to trading fees

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#2284]
With the current fee settings, we can chanrge up to 0.63% as trading fees, this makes the mimimal order size pretty big when gas price and ether price is high. I propose to apply a const factor *f* to it, so when the fee precnage is *x*, we always apply *fx*. We can choose *f=4* to charge up to 2.54% trading fees and reduce min-order size by 4.

**Comment by Brechtpd** [comment]
There's 1 unused bit in 3.6 we can use to enable this factor (this bit was used in 3.1 to use the fee value as rebate, but rebates were removed in 3.6 so unused now). This bit is currently always set to 0. So by just using that 1 bit extra as normal we could enable up to 1.27% in steps of 0.01%, but I guess that's not that much of an improvement.

If we use that bit as "factor disabled/enabled" the on-chain data remains nicely backward compatible as well. Maybe _f=10_, basically turning the 7-bit fee value in a 7-bit decimal float with 1 bit exponent and 6 bit mantissa? Would still allow up to 0.63% in steps of 0.01%, but also up to 6.3% in steps of 0.1%, maybe preparing for the worst.
