### ISSUE TITLE
FLI-ETH Pair not available in v3.6

### ISSUE THREAD

**Issue by jkel92** [Loopring/protocols#2292]
Potentially the UI is not updated, but its not showing as an active pair in pools or the exchange.

**Comment by dong77** [comment]
It may be caused by the fact that the pool's total liquidity hasn't reached the required threshod of 4K USD. @lyddream please confirm.

**Comment by lyddream** [comment]
![image](https://user-images.githubusercontent.com/11224316/112321509-09875780-8ceb-11eb-93a8-8afe337a93ac.png)
I have confirmed that it's because that the total liquidity hasn't reached the required threshold of 4K USD.
