### ISSUE TITLE
Not enough Ether to pay transaction gas - press Enter to try anyway

### ISSUE THREAD

**Issue by TheJollyLaMa** [Loopring/protocols#2341]
V2     https://exchange.loopring.io/account/balances

In the "Make a deposit" popup view, a user cannot press the "Deposit" to make a deposit unless they have enough eth for gas in their wallet - as should be.

But if you press the enter key, the transaction kicks over to metamask anyway, even though the deposit button is shaded out and you do not have enough eth for gas.

- just a small hiccup as there doesn't seem to be any other dysfunction or real ramification.  User still cannot confirm in metamask without enough eth for gas but I would think, if the submission button is deactivated in the loopring platform, the keyboard submission should be too.

**Comment by xiaowheat** [comment]
Do you have a screenshot? What token do you deposit?

**Comment by TheJollyLaMa** [comment]
It was with DAI in Chrome buuttt....
something's changed for the better, it's no longer happening, and the text "DAI" turns red now as an indicator.
So all is well!
