### ISSUE TITLE
DEX operator not enforced to handle `createOrUpdateAccount`

### ISSUE THREAD

**Issue by autumn84** [Loopring/protocols#246]
<img width="614" alt="屏幕快照 2019-07-01 下午7 33 42" src="https://user-images.githubusercontent.com/5515468/60433530-a365c180-9c37-11e9-979f-8d6bf52968b8.png">

As seen above: DEX operators seem not to be enforced to handle the `createOrUpdateAccount` on-chain requests as these requests do not involve on-chain 0-amount deposits. 

@Brechtpd please confirm if this is the case. If so, we can either implement this method by calling `updateAccountAndDeposit` with 0-amount or remove this method (togetehr with `creatAccount` and `updateAccount`.

**Comment by Brechtpd** [comment]
This is indeed the case and I was aware of this. This is why the `updateAccountAndDeposit` is the more useful method.

The method (and all other methods not updating the Merkle tree) could be useful in some limited cases. Like when you just setup a new account for an exchange without having to deposit anything (so there is no cost for the Merkle tree update so just creating an account is cheaper, you can only start trading after a deposit so this still works) but I'm totally okay with removing it, when I discussed this with @dong77 he still found them useful, but if he's okay with it we can just remove them.

**Comment by Brechtpd** [comment]
I have implemented this by using `updateAccountAndDeposit` in `createOrUpdateAccount` because the simpler API still makes sense.

In all cases `depositFee` is paid, but on top of this an **additional** `accountCreationFee` is paid for new accounts or an **additional** `accountUpdateFee` is paid when the public key was updated.

**Comment by dong77** [comment]
these changes all look good to me, Brecht.

**Comment by dong77** [comment]
This is implemented in #241
