### ISSUE TITLE
Shutdown mode problem

### ISSUE THREAD

**Issue by zerochl** [Loopring/protocols#2519]
When shut down mode happened, project side can withdraw the staked token. then project side make off, user will pay much gas to withdraw.

**Comment by Brechtpd** [comment]
Sorry for the late reply, forgot to answer when I first saw this.

The main idea behind the shutdown feature is that the exchange can indeed be shutdown at any time, but not without warning users well in advance. If `shutdown` is called, the exchange needs to keep working for *at least* `MIN_TIME_IN_SHUTDOWN` seconds just like before `shutdown` was called, so users can still count on the same guarantees as before for a limited amount of time. Users should make the most of this period to withdraw their funds from the exchange using the normal withdrawal methods.

But we cannot force operators to stick around forever if they don't want to. And so eventually users that did not withdraw their funds normally in time still have the option to withdraw in withdrawal mode, which indeed has a high cost when gas prices are high. However, at normal gas prices (10 gwei, ETH $2000) the cost per withdrawal is around $50. Obviously expensive, but still feasible for most users.
