### ISSUE TITLE
[Protocol3] Problem distributing to non-existing accounts in shutdown

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#260]
Sometimes an account is used to send tokens to another account that does not need to sign something off-chain or isn't triggered by an on-chain request (the operator or the wallet). In cases like this it's possible `accountID >= accounts.length`. This is fine in almost all cases, the funds are lost or are locked up until the account is created.

In shutdown mode however, these funds need to withdraw to reset the Merkle tree. This causes 2 things:
- There is no account associated with the accountID so we would have to make sure we check that `accountID <  accounts.length` when distributing the tokens, and otherwise send the tokens to e.g. the protocol fee pool.
- We give extra time for the withdrawals the more accounts are created. We won't give extra time in this case because we don't know on-chain the account exists.

We can solve this by either
1. don't care about the slightly wrong estimate how much work is needed (which isn't a very good estimate anyway because the work required to reset an account can wildly differ) we just make sure that withdrawals don't fail when `accountID >= accounts.length`.
2. not allowing funds to be sent to accounts with `pubKey == 0` because that's the value for accounts that were not created yet. We simply disallow setting the pubKey to 0 when creating an account. We still allow setting an invalid pubKey to disallow signing, users just need to use a different value (e.g. `pubKey == 1`).
3. checking if `accountID < accounts.length` for all accounts that don't have to sign anything in the circuits.  We would have to pass  `accounts.length` to the circuits and do a slightly more expensive 'less than' check.

I think options 1 and 2 are the best because they are the easiest to implement. Option 1 is I think good enough to fix this issue, though it doesn't hurt to do option 2 because it's easy.

**Comment by dong77** [comment]
I would vote for option#2, in the meanwhile, maybe we should make sure `accontID < accounts.length` always holds?

**Comment by Brechtpd** [comment]
I implemented option 1 in #263 .

With the updated fee model only the operator will be able to receive fees on any account, and the operator will be controlled in some way by the DEX. So by using an invalid accountID in this case
- the operator does not receive the fees for the block
- the DEX makes the shutdown procedure more expensive for itself

In the current fee model the wallet account ID could be chosen freely by users which could be abused, but that will not be possible any more in the updated fee model.

Maybe still a good idea to do option 2, but we can do it when implementing the updated fee model.

**Comment by dong77** [comment]
Ok. But let’s keep this issue open and revisit it after the fee model is upgraded

**Comment by dong77** [comment]
Fixed with option 1&2 implemented.
