### ISSUE TITLE
[Protocol3] Pluggable Block Types

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#289]
In our current design, there are some block-type specific logics to check the validity of blocks based on their types. I propose to migrate these logics to block's own smart contract and maintain a mapping between `blockTypeId` to the address of these block specific smart contracts. The mapping can be modified by the owner or later by the Loopring DAO. With this **pluggable block types**, we can enrich the protocol with new types of blocks such as privacy-preserved settlement and derivatives trading.

block type ids should replace the current block type enumeration and only be reused if the block's data scheme is fully compatible with the previous version.

Certain blocks such as on-chain deposit and withdrawal may be hardcoded into the main smart contract and become un-upgradable.

**Comment by dong77** [comment]
@Brechtpd I talked about this with @kongliangzhong, he will follow up with an implementation.

**Comment by dong77** [comment]
@kongliangzhong please also reference issue #294

**Comment by dong77** [comment]
@Brechtpd After my attempt to implement this and thinking after your feedback, I feel like we should simply use OwnedUpgradeabilityProxy to make sure the entire `IExchange` is upgradable.

**Comment by Brechtpd** [comment]
@dong77 I also think that's the best idea.

**Comment by dong77** [comment]
ok. I’ll close this issue then. Going forward let’s use proxy to achieve upgradability.
