### ISSUE TITLE
[Protocol3] Potential ring settlement & fee calculation bug

### ISSUE THREAD

**Issue by kongliangzhong** [Loopring/protocols#314]
In operator/state.py#settleRing method, assume ring.orderA.buy = false and ring.orderB.buy = false. Than ring.orderB is takerOrder, ring.OrderA is makerOrder.
But, when calculating fees, protocolTakerFeeBips is used, as shown in the code below:
```
        (fee_A, protocolFee_A, rebate_A) = self.calculateFees(
            fillA.B,
            ring.orderA.feeBips,
            context.protocolTakerFeeBips,
            ring.orderA.rebateBips
        )

        (fee_B, protocolFee_B, rebate_B) = self.calculateFees(
            fillB.B,
            ring.orderB.feeBips,
            context.protocolMakerFeeBips,
            ring.orderB.rebateBips
        )

```

So maybe we should use the timestamp of an order to decide if it is a taker order or maker order.  If orderA.timestamp < orderB.timestamp, then orderA is taker, otherwise it is maker.

**Comment by Brechtpd** [comment]
Why is ring.orderB the taker order here? The rule it that the second order (orderB) is always the maker order.

Is it  because we do this in the code?
```
if ring.orderA.buy:
   (spread, matchable) = self.match(ring.orderA, fillA, ring.orderB, fillB)
   fillA.S = fillB.B
else:
  (spread, matchable) = self.match(ring.orderB, fillB, ring.orderA, fillA)
  fillA.B = fillB.S
```

This is an implementation detail to reuse the same matching code in all cases, but orderB is still the maker order. The ring settlement will use the price of orderB to settle the ring.

**Comment by kongliangzhong** [comment]
@Brechtpd , Yes, I think it is a mistake in the implementation.

**Comment by Brechtpd** [comment]
Can you give the ring that gives unexpected results? So a ring where the ring settlement doesn't use the price of orderB for the settlement? Otherwise I have to find one myself for testing. :)

**Comment by kongliangzhong** [comment]
I am sorry, my bad. I think you are right, If orderB is always the maker order, then it makes sense for the example:
![image](https://user-images.githubusercontent.com/1477179/62096793-70a2fd80-b2b7-11e9-84d2-e052e8b18e6d.png)
This ring was expected to be full filled.
