### ISSUE TITLE
[Protocol3] Generic Extension for Request Validation (GERV)

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#318]
This is interesting:
- https://medium.com/starkware/starkexchange-fast-withdrawals-using-cookie-jars-88eefea6a11a

This allows withdrawals before a block is proven.

I think we can do something similar like this with minimal changes:
- The user does a withdrawal (on-chain/off-chain) like usual
- The withdrawal is included in a block and the approved withdrawal data is stored on-chain (but the block is not yet proven)
- The user wants to do a fast withdrawal so requests the withdrawn tokens through the cookie jar contract, the contract checks the approved withdrawal data for the user (accountID, tokenID, amountWithdrawn), if the cookie jar has enough funds to do this transfer:
  - The cookie jar immediately sends the tokens to the user using the funds stored in the cookie jar contract.
  - The accountID in the approved withdrawal data is changed to the account of the cookie jar contract so once the block is proven the cookie jar contract receives the tokens it 'borrowed to the user

The cookie jar contract is operated by the exchange so of course the exchange trusts itself to submit a valid proof for the block. If not, the exchange loses the funds (and the user is happy because he can withdraw the funds again! User funds remain safe.).

The user probably needs to approve this somehow because this could be a security risk for users if the cookie jar contract is malicious. The approved withdrawal data could maybe include a single bit if the user allows these fast withdrawals. Or the cookie jar contract cannot be changed easily for an exchange/needs to be approved by the Loopring contract/...
EDIT: the token transfer from the cookie jar contract to the user can be done in the exchange contract which makes it secure for users even without having to trust the cookie jar contract, no approval from users needed. The only change for users is that they get their tokens earlier than they would otherwise, which is only a benefit.

Could be useful, though the number of withdrawals we can do in a single block is very limited by the approved withdrawal data because we need to store that onchain (which is expensive), currently max ~1800 withdrawals/block so the time to prove a block like this will be quite low to begin with.

**Comment by dong77** [comment]
This is a great idea. Let me write down my understanding so @letsgoustc  and @kongliangzhong  can understand it well.

For on-chain deposits and withdrawals, the handling of these requests can be included in blocks for ZKP when and only when there are corresponding requests on-chain. This means the on-chain requests the "conditions" for including these Merkle tree updates, if these conditions are not satisfied (meaning there are no on-chain requests), then the Merkle tree updates cannot be forged and included in a block. You have to realize: the on-chain requests are created first, then the offchain tree updates are created (by the operator) afterward.

The idea behind the above link is that: first, a user creates and authorizes off-chain requests that represent the transfer of X tokens from the user account to the operator's account; but this off-chain requests can only be included in blocks on the condition that there is an on-chain transfer of at least X token from a predefined, DEX owned address to the user. The conditions will always need to happen FIRST than the circuits actually handles the request. And in this case, the conditions are the "Fast withdrawals".

**Comment by dong77** [comment]
@Brechtpd, If my understanding is correct. It seems from the user's perspective, requesting fast withdrawal doesn't have to involve any on-chain transaction, but only a "conditional" off-chain request. This will make a fast withdrawal take only 1 block time.

**Comment by Brechtpd** [comment]
Yes, this will allow withdrawals in 1 block time.

There's a couple of ways this can be implemented, I'm not sure yet what's the best way. Only an off-chain request could work.

The way I described it in my first post allows any withdrawal request (on-chain or off-chain) to be a fast withdrawal without any changes to the circuits, only some additional on-chain logic to modify the approved withdrawal data. But this was just my first idea to get this to work with minimal work.

**Comment by dong77** [comment]
I see. But if we want to provide fast withdrawal, let's make it truly fast :) The idea fascinates me.

**Comment by dong77** [comment]
For fast withdrawals, one party may not have enough tokens of various types, maybe we can design the cookie jar so that anyone can create an account then create his own cookie jar...

**Comment by Brechtpd** [comment]
If you have access to extra funds, why would you put them in a cookie jar contract to get them out of the exchange faster? You already have access to those tokens, you don't get access to more tokens using this?

I think it could also be risky if the cookie jar contract is managed by someone else than the DEX itself. Let's say the off-chain balance of the user is only 1ETH, but the user requests a withdrawal of 10ETH. The DEX will not allow a fast withdrawal of 10ETH because the DEX's offchain balance can only be increased by 1ETH, so the DEX would lose 9ETH (this money is already gone with an on-chain transfer before it can be checked against the offchain state). If the DEX doesn't pay this fast withdrawal then he doesn't really need to care about this. The exchange may have to go into withdrawal mode because of this (depends on how this is implemented) but there's a risk for the cookie jar contract owner to lose money (instead of a very small risk for the DEX itself which it has complete control of).

**Comment by dong77** [comment]
The idea is to create a solution when the relayer does not have enough token for fast withdrawal. I imagine someone who has enough of certain token would be happy to provide a fast withdrawal pool to make money. Ideally the fund providers don’t have to trust the relayer but I have not yet figured out a solution. 

I think in general the cookie jar is similar to the hot wallet in CEXex, they are hot and used for fast withdrawals, and they have the same security risks. If the exchange got hacked they may be both gone.

**Comment by dong77** [comment]
@letsgoustc I’m assigning the fast withdrawal feature to the engineers in Shanghai to implement.

**Comment by Brechtpd** [comment]
Continuing discussion from #464 

We can make the system more general with the internal transfer method (main ideas come from a Starkware talk). This makes our exchange contract act more like a general wallet for users.

### General payments

We can add support to fast withdraw to any address, not just the owner of the account. The recipient address is simply part of the offchain fast-witdrawal request and this data is also stored in some way on-chain so we chan check this in the circuit eventually.

### General interactivity with other smart contracts

We can go even further and allow a user to request the operator to call any smart contract function with some data. This can simply be a call on a token transfer contract for a simple withdrawal or a payment to a different address as described above, but it can also call any function on any smart contract. The contract address + ABI encoded call data is hashed and this hash is part of the fast-withdrawal off-chain request message. The operator executes this on-chain and the address + ABI encoded call data is again hashed on-chain so we can verify if the operator executed what was requested by the user. If the operator did this he can use the off-chain request to do an internal transfer to get the payment from the user for this. Note that this smart contract call may fail just like it would if the user would do directly from his own Ethereum wallet, the operator can still get paid.

This would be great because a user would have almost the same flexibility as storing his ETH/tokens directly in his Ethereum wallet (in some ways even more flexibility because he does not need gas to pay for the on-chain interaction, he can use any token/ETH to pay the operator).

**Comment by dong77** [comment]
I like the idea of general payment.

The “general interactivity with other smart contracts” concept is also interesting, the main concern I have is security. The operator's address calling an arbitrary contract may expose great risks for the operator, and I don't know a way such that the operator can call FOR the user's address.

My concern echos what's said here https://github.com/iurimatias/TransactionRelay:
> Since the relayer is the one doing the transaction, then the contract will see msg.sender as the address of the relayer not the issuer. It's possible to put a signature in the transaction itself but a contract would need to know how to deal with this. Another alternative is to deploy a proxy contract > A that has permissions to interact with another contract B. contract A can verify the signature and then interact with contract B.

The security issue may be mitigated if [EIP 1613](https://eips.ethereum.org/EIPS/eip-1613) get resolved.

**Comment by Brechtpd** [comment]
> The “general interactivity with other smart contracts” concept is also interesting, the main concern I have is security. The operator's address calling an arbitrary contract may expose great risks for the operator

The operator can drop any request it wants. He can just whitelist a couple of contract addresses he actually wants to process and drop all others. It's an extra feature the operator can provide, not a basic functionality users can depend on.

> and I don't know a way such that the operator can call FOR the user's address.
> 
> My concern echos what's said here https://github.com/iurimatias/TransactionRelay:
> 
> > Since the relayer is the one doing the transaction, then the contract will see msg.sender as the address of the relayer not the issuer. It's possible to put a signature in the transaction itself but a contract would need to know how to deal with this. Another alternative is to deploy a proxy contract > A that has permissions to interact with another contract B. contract A can verify the signature and then interact with contract B.
> 
> The security issue may be mitigated if [EIP 1613](https://eips.ethereum.org/EIPS/eip-1613) get resolved.

That's a good point. Users may not understand that it doesn't work exactly like a normal Ethereum transaction. This also limits what can be done with it. But it seems like people are working on it (and contracts may get additional APIs to work around this because L2 solutions like this will no doubt be popular in the future).

**Comment by dong77** [comment]
We can design for the future in terms of contract interfaces and off-chain request format. But for now in production, as you said, we should only allow certain contracts to be called. This whitelist should initially be managed by us not the operator as they may be evil and users who lost funds because of this will likely hold us responsible for it.

**Comment by dong77** [comment]
@Brechtpd do you recall that someone we talked about/to has the "gas station" idea, it enables people (clients) to sign Ethereum transactions and a relayer will broadcast the transaction with gas, probably by wrapping the original transaction with another transaction. I don't recall their design but I think it may be a source of reference.

**Comment by Brechtpd** [comment]
I think that's a great idea. It would be great if deposits would also work in the same way. I've been wondering for a while if an off-chain deposit request could be useful. The only unfortunate thing here is, at least I think it's not possible, is that a contract can't set the ERC20 allowance for a different address, so the user will still need to manually set the allowance himself if he wants to deposit from his Ethereum wallet.

We already support gas-less withdrawals by using off-chain withdrawals/fast withdrawals. The main reason for the on-chain withdrawals is to force the operator to include it (and go into withdrawal mode if he doesn't want to), so when the exchange behaves normally on-chain withdrawal requests won't be used because they are less efficient.  So a meta tx for on-chain withdrawals makes less sense because the off-chain withdrawal request will be cheaper and supports paying the fee in any token. If it's trivial to also support withdrawals it may still make sense to support it.

**Comment by dong77** [comment]
I agree that the off-chain withdrawal will make meta-tx based withdrawal meaningless.

But I guess the off-chain deposit is still interesting to me, although the initial allowance must be set by the user first. The challenging part is that there is no way the operator knows how much to deposit because here may be race conditions -- while the operator tries to deduct the token from the user's account, the user can also try to spend the token.

**Comment by Brechtpd** [comment]
> The challenging part is that there is no way the operator knows how much to deposit because here may be race conditions -- while the operator tries to deduct the token from the user's account, the user can also try to spend the token.

In any case it will need to be build on top of the same mechanism we use now for the reasons you mention. The transfer + the amount stored on-chain that is used to increment the user's balance in the Merkle tree needs to be done in a single Ethereum transaction, just like deposits are done now. We can't use the trick like with the fast withdrawals where the operator knows that the account balance can't be changed unless the operator himself does it. But a similar trick CAN be done for the fee payment. 

The user can still be spend the tokens directly from his Ethereum wallet before the operator submits the request on-chain of course, but if the user has any balance for the fee token in his account a fee could still be charged for the failed deposit, so this could be defence mechanism for the exchange, though this probably won't be a problem in practice.

So I think it could work something like this:
- User signs the deposit request with his ECDSA key (not the EdDSA key, this signature isn't used in the circuits, only on-chain). The operator uses this signature to do the deposit on-chain for the user and allows the operator to transfer tokens from the user into the exchange. The deposit is now in the deposit queue and everything else pretty much works the same way for the deposit on-chain.
- When the deposit is handled in the circuit we could charge the user a small fee from his off-chain balances. This can be taken from the amount that was just deposited (100% sure this will be available if the deposit went through when the fee is getting paid so anyone that provides this service can count on it that it can be paid) or some other balance the user has.

I think it should be possible to implement this with the meta transactions mechanism described above.

None of this works with ETH of course, ETH always needs to be deposited with our current method.

**Comment by Brechtpd** [comment]
High level overview of how I'm currently implementing this and why. 

The goal is to allow the exchange functionality to be as flexible as possible to allow things like fast-withdrawals, but also to allow the exchange to be used by users with as few onchain transactions by the users themselves. This can be done either by allowing the exchange to do the necessary transactions for them or by letting the users use existing gas station networks.

The main idea to only implement the main building blocks inside the exchange. Additional functionality is built on top of the exchange contract inside what I currently call the Relayer contract. The Relayer contract is allowed to call functions on the Exchange contract which would normally only be allowed to be called by the account owner. Of course, this will only be allowd if the Relayer has some other sort of approval from the account owner like a signature. On the Relayer contract additional modules (implemented in contracts) can be added/removed to add/remove functionality.

### Authentication

```
function isAuthorized(
    ExchangeData.State storage S,
    address accountOwner
    )
    internal // inline call
    view
    returns (bool)
{
    return msg.sender == accountOwner || msg.sender == S.relayerAddress;
}
```

As explained above, the Relayer is authorized to do the same operations as the user. We don't need any interface for the relayer in the Exchange contract (nothing is ever called on it), we only need its address.

### Exchange building blocks

The main difference here is that we add function variations with an `address from` and we check if `from` authorized the operation. We don't use any signatures checks in the Exchange contract for this. The reason is that in most cases a user would have to sign multiple requests if we do it like that and we would have to do all the `nonce` logic in the Exchange contract as well (otherwise the signature could be used multiple times in a replay attack). In a fast withdrawal for example, the user already will sign how much he wants to withdraw, and then he would also need to sign some data to approve the onchain internal transfer as well. This is not user friendly so we depend on the Relayer contract to do this instead because the Relayer contract has all the necessary context.

`internalTransferFrom` has a `requestHash` parameter which I'll explain below. 

```
function depositFrom(
    address from,
    address to,
    address token,
    uint96  amount,
    address feeToken,
    uint96  fee
    )
    external
    payable
    nonReentrant
{
    // Needs to be authorized here because the token transfer is done immediately
    require(isAuthorized(from), "UNAUTHORIZED");
    state.depositFrom(from, to, token, amount, feeToken, fee);
}

function internalTransferFrom(
    address from,
    address to,
    address token,
    uint96 amount,
    address feeToken,
    uint96 fee,
    uint requestHash
    )
    external
    payable
    nonReentrant
{
    // Authorization can be done onchain of offchain 
    // (no state change done here is irreversible, so immediate authorization isn't always necessary)
    if (!isAuthorized(from)) {
        require(requestHash != 0, "UNAUTHORIZED");
    }
    state.internalTransferFrom(from, to, token, amount, feeToken, fee, requestHash);
}

// Allow the relayer contract to do payments using the onchain balances of the user.
// This way the user only needs to approve a single exchange contract for all exchange/relayer features.
function onchainTransferFrom(
    address from,
    address to,
    address token,
    uint96 amount
    )
    external
    nonReentrant
{
     require(isAuthorized(from), "UNAUTHORIZED");
     state.onchainTransferFrom(from, to, token, amount);
}

// Functions like withdraw, ... can be done similarly

```

Deposits and onchain internal transfers use the same queue and are handled by the same circuit. A deposit is handled as a transfer from account 0 to the account that needs to be topped up. `deposit` is still a separate external function because deposits are still special (we need to be able to withdraw from them in withdrawal mode, it's critical that the correct amount is deposited otherwise the exchange may not be solvent,...).

Note that the internal transfer may not be able to transfer the requested funds from the account (e.g. for a fast withdrawal the amount requested by the user may be 10ETH, but the user may only have 1ETH. The operator takes the risk that the requested transfer amounts are actually possible, if not the maximum possible will be transferred). A fee can also be paid in any token from the offchain balance of the user to the operator (so in the context of a single operator/exchange: the operator pays the onchain fee for it, gets the onchain fee back when the block is finalized, but receives the fee paid offchain).

### Relayer

For the Relayer we can use a module based approach. Modules can be added/removed from the Relayer contract. Every module contract is called with `delegatecall` so that `msg.sender` remains the relayer address. All modules also share state this way (all state is stored in the Relayer contract).

Some possible modules:

#### Fast withdrawals

We can create a dedicated module just for fast withdrawals. We need the following operations:
- Check the ECDSA signature of the user against the fast withdrawal data
- Transfer the tokens from the cookie jar contract (we can use a simple authorization here like `tx.origin == approvedAddress` so that only approved addresses can transfer funds out of the contract)
- Check if the `from` address equals the recovered address from the signature. If so, call `internalTransferFrom(from, ....).
- Guard against replay attacks: Increase the **onchain** nonce of the user or store the request hash onchain and make sure this hash wasn't seen before yet.

The ECDSA signature check and the guarding against replay attacks are some onchain costs we can move offchain like this:
- The user signs with EdDSA instead so we can check the signature offchain in the circuit. The hash of the request is part of the data that is being signed by the user.
- The nonce of the account in the Merkle tree is used instead to guard against replay attacks.
- As part of `internalTransferFrom` we pass through the request hash. This request hash needs to match the request hash in the EdDSA signed request, otherwise the internal transfer isn't done (but it can still be included in a block, otherwise the request chain would get stuck on this request!). 

The ECDSA method is useful in some cases because the user can sign requests that can be executed in any order. If that's the case we need to use the method of storing the hash onchain because with nonces we're stuck with a fixed sequence.

#### Integration with gas station networks

See [gsn](https://gsn.openzeppelin.com/) for example. Different gas station networks will have different APIs. If we want to support a gas station network like this for users we can do the necessary logic in a module and forward the authorized requests from the user to the exchange.

#### General conditional transfers using onchain data

The user can sign a message for a transfer once something happened onchain. So the request signed by the user could be something like 'if the price of ETH drops below $100 on uniswap do a fast withdrawal to a certain address`. Things like this could be useful to integrate more seamlessly with existing defi smart contracts. Functionality like this would need to be supported by the exchange itself in most cases (as the operator needs to monitor for this onchain and only the operator can 'lock' the amount offchain so the internal transfer can 100% be done).

#### General meta transactions

A module can implement general transactions with fees paid using offchain or onchain balances. We do have to watch out here that we intercept all calls to an exchange and verify that the `from` address has authorized this. To simplify this we can just do all calls in a different contract (so that `msg.sender != relayer.address` for these calls) but the relayer can still request the fee payment from the user using `internalTransferFrom` or `onchainTransferFrom` from the relayer address.


### Circuits

To allow this more generalized functionality onchain I am creating a single circuit that handles all the logic currently handled by the deposit circuit combined with the additional logic for the internal transfers. This way we can use a single queue onchain for both types of requests. Do note that this increases the cost of the deposit circuit of about 70,000 constraints to something like 100,000-125,000 constraints (some optimizations may be possible). There is also a small additional gas cost because the internal transfer needs onchain DA because the amounts available onchain may not be possible (but for deposits this onchain data of ~12 bytes can be set to 0, so the additional gas cost is only `4*12 = 48 gas`.

I think this should be fine because flexibility seems to be more important for these operations than the additional offchain proof generation cost. Poseidon and the reduction of the calldata costs changed what is possible while keeping the costs low. It could even be more efficient because by combining the functionality we can create larger blocks which reduces the number of blocks we need to commit and verify (as gas prices are much higher now than what they were, but hard to predict if that will still be true in the near future).

But we can go further. The cost of onchain withdrawals isn't very important because those will almost never be used. We can handle withdrawals similarly like we handle deposits: withdrawals are just transfers from an account to accountID 0 (but we do have to have keep track of those because we need to store the approved withdrawal data onchain so we can withdraw from it later).

Adding support for offchain withdrawal requests and offchain internal transfers is almost no work then. Order cancellations support would also be quite easy to add.

Note that it's possible to do onchain requests as well as offchain requests in a single block (the best way I have currently found which allows this, while keeping our existing chain structure, is to do the onchain requests (if there are any) at the start of the block, the remaining slots can be used for offchain requests).

So my conclusion would be that maybe we can limit ourselves to just 2 (maybe 3) circuits:
1. The ring settlement circuit: Needs to be as scalable and cheap as possible. 
2. All other functionality: either onchain requests (which are inherently not very scalable anyway so we **at most** would only need to handle 10s of these requests/second) or less important/frequent by nature (order cancellations, offchain withdrawals, maybe internal transfers).
3. (Optional) Offchain internal transfers (If necessary because frequently used). These could also be done with circuit 2. but doing it like that increase the proof generation cost ~x2 (~50,000 constraints to ~120,000 constraints, mainly because of the overhead of sha256 hashing necessary for onchain requests).

This way can either do less trusted setups, or the same number of trusted setups but with more blocksize for our limited set of circuits.

Note that we can still handle requests like we do now (split across the different rquest types). This is just added flexibility which can be used by lightcone/... And we can always keep/add back dedicated circuits for certain request types.
