### ISSUE TITLE
[Protocol3] Support miss transfer or air drop

### ISSUE THREAD

**Issue by hosschao** [Loopring/protocols#327]
Our current protocol doesn't support:
1.  Give back token amount which user directly transfer to smart contract address.
2. Get air dropped token.

Maybe we could modify protocol to support these: Like smart contract could send all tokens which not supported by our exchange to an address.

**Comment by dong77** [comment]
@hosschao  please see #201. This not a priority. I'll mark this as a duplicate issue.
