### ISSUE TITLE
[Protocol3] try recursive snarks verification 

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#341]
Try recursive SNARKs - https://ethresear.ch/t/reducing-the-verification-cost-of-a-snark-through-hierarchical-aggregation/5128.

**Comment by Brechtpd** [comment]
Currently 2 options:
- MNT4/6 curve (this will make most calculations more expensive)
- [SNARK recursion without pairing cycles](https://github.com/zcash/zcash/issues/4092)

**Comment by dong77** [comment]
I've moved the discussion to a WIKI page - https://github.com/Loopring/protocols/wiki/More-On-ZKP
