### ISSUE TITLE
[Protocol3] SUPER blocks™

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#362]
I don't think we should do this but it's an interesting idea so I'll just leave this here for reference and discussion. This would increase the throughput without DA by ~2x after Istanbul, with DA there will be a much smaller gain. This would add quite a lot of complexity for not much gain with DA which should be our main concern. With recursive SNARKs this is also not really needed I think.

A large cost of committing blocks (without DA, with DA it's the calldata cost) is storing the block meta-data onchain, so reducing this cost is a good place for optimization.

For blocks that only modify the off-chain state like ring settlements and simple token transfers we can store multiple blocks (that are exactly the same) into a single on-chain block (stored in the `Block` struct):

```
struct Block
{
    // Merkle root of the last block
    bytes32 merkleRoot;

    // This will store the public data hashes of all the blocks hashed together
    bytes32 publicDataHash;

    // Single block state for all the blocks (all blocks need to be verified together)
    BlockState state;

    // All these values need to be the same for all the blocks
    BlockType blockType;
    uint16 blockSize;
    uint8  blockVersion;

    // timestamp the block is created onchain, so is the same for all blocks
    uint32 timestamp;
    
    // The following values remain unchanged for 'off-chain' blocks
    uint32 numDepositRequestsCommitted;
    uint32 numWithdrawalRequestsCommitted;
    bool   blockFeeWithdrawn;
    uint16 numWithdrawalsDistributed;
    bytes  withdrawals;
}
```

In `merkleRoot` we store the merkle root of the latest block of the batch (making sure that all the blocks in the batch follow a valid `oldMerkleRoot` -> `newMerkleRoot` chain). In `publicDataHash` we store the hash of all the public data hashes of all the blocks.

All the blocks inside this SUPER block need to be verified together because we only have a single `BlockState` (so all blocks need to go from `COMMITTED` to `VERIFIED` at once to correctly update this state). All the public data hashes of the blocks also need to be sent onchain and these values are hashed and checked against the `publicDataHash` stored onchain.

**Comment by dong77** [comment]
This is a pretty interesting idea. I agree with you that 1) this is going to complicate the design, and 2) we focus on DA to provide the best security.

**Comment by dong77** [comment]
@Brechtpd I closed this issue, but you feel free to reopen it if you believe the idea is still worth exploring.
