### ISSUE TITLE
[Protocol3] Ideas to improve LRC user staking

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#401]
I have some ideas to improve the current user staking design. Let me use the following drawing to illustrate my ideas.

![WechatIMG714](https://user-images.githubusercontent.com/1710087/62836662-87d8d800-bc33-11e9-8f8b-a1f3086fdbd9.jpeg)

-  We need first define something called **token staking age** or **token age**, which is the average duration a user's LRC has been staked into the staking pool. If the user made multiple deposits at different time, the staking age will be averaged out.
- Staked LRC can be withdrawn at any time, and partial withdrawals won't change the token age of the remaining LRC. However, there will be an early withdrawal penalty if the token age is smaller than 6 months (the penalty will be sent to the fee vault.), which should be known as the **minimum staking duration** or **maturity time/period**. The penalty will be a percentage of the token to be withdrawn, the **penalty percentage** will be calculated as follows:
```javascript
const MAX_PENALTY_PCTG = 50;
penaltyPctg = MAX_PENALTY_PCTG * (minStakingDuration - tokenAge).min(0) /
    minStakingDuration;
```
- we can introduce a **reward cycle** concept (which is 3 months in the drawing). LRC reward can only be claimed by a user whose token age >= one reward cycle during the next 3 days after each reward cycle known as the cycle's **open window**.
- A user can only claim the reward in whole. The reward claim has two side effect: 1) the claimed LRC will be automatically re-staked which will reduce the token age, 2) the user's token age will be reduced by another 3 months (one cycle) to force the user to stake for another cycle.
- A user can deposit at any time and his points will start to accumulate regardless of where he is in the cycle.  The points represent his total share of LRC he can claim in the next cycle's open window. The points will be zeroed out when he made a claim.
- A user can decide not to claim in an open window, in that case, his points will remain and be eligible for claiming LRC in future open windows.
- Withdrawals won't affect points already accumulated.

**Comment by dong77** [comment]
Comparing to the current implementation:

- The current implementation allows claiming at any time, this is flexible but the users won't have a time window to focus on claiming and talking about this topic. I believe a well scheduled time window to bring LRC token holders' attention is great for PR and community activities. Besides, if the open windows are small, it is really easier to manage user's expectations and deliver encouraging news.
- The new implementation also introduces a risk factor -- losing LRC for earlier withdrawals. This is good for the "non-security" aspect of LRC.

I'd like to know your thoughts, @mfinestone @letsgoustc @kongliangzhong. 
If we decide to go to this direction, @kongliangzhong you may have to implement this for me.

**Comment by letsgoustc** [comment]
Propose a simple staking mechanism here:

1. Every 172800 ethereum blocks (Which means 30 days) we open a staking window for any user. The staking window can be set to 5760 blocks(means one day). During the staking window, any user can stake any amount LRC. 
2.After 172800 blocks, all staking users in this period will get the protocol fee according to average staking units. Ra = Total Fee * Ua / sum of all U.
3. We allow user to claim staking at any time, but if user does claim, no matter how much, all user's staking will be removed from the final return calculation.

**Comment by dong77** [comment]
As we have finalized the design for LRC staking in 3.0. I'll close this issue unless in the future we want to optimize the overall user staking design.
