### ISSUE TITLE
[Protocol3] SNARKs with universal trusted setup

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#453]
- [Sonic](https://eprint.iacr.org/2019/099.pdf)
- [Spartan](https://eprint.iacr.org/2019/550.pdf)
- [PLONK](https://eprint.iacr.org/2019/953.pdf)
- [Supersonic](https://twitter.com/benafisch/status/1171688193177137153)
- [Marlin](https://eprint.iacr.org/2019/1047.pdf)
- [DARK](https://www.youtube.com/watch?v=m3Cc0kuzhfg)

With PLONK being the cheapest and most interesting one, but still significantly more expensive than groth16 (1.5x to more than 4x more expensive to generate the proofs depending on the circuit, because of how Poseidon works I think it will be much more expensive for us). The cost for verifying the proof on-chain is comparable to groth16.

**Comment by dong77** [comment]
I've moved the discussion to a WIKI page - https://github.com/Loopring/protocols/wiki/More-On-ZKP
