### ISSUE TITLE
[Protocol3] Optimistic Rollup

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#466]
- https://medium.com/plasma-group/ethereum-smart-contracts-in-l2-optimistic-rollup-2c1cef2ec537
- https://vitalik.ca/general/2019/08/28/hybrid_layer_2.html

I'm not the biggest fan of this approach because of the worse security properties and very long finalization times (multiple days instead of 1 to 2 hours max). So it's only interesting of the cost savings are very large.

I don't fully understand the approach yet, but this could be interesting to reduce the cost of generating the proofs significantly, but with worse security guarantees (because we would need to depend on people monitoring the state transitions). So our current approach is still the most secure, but more expensive because full proofs need to be generated for each block. 

The reason we cannot depend on fraud proofs even when data availability is used is that we only publish the data on-chain that is needed to update the Merkle tree. There is not enough data on-chain so that anyone can check if the state transition in a block is valid, this is why the operator needs to post the proof himself (only he is guaranteed to have all the request data, signatures, etc... that were used in the block).

#### An idea that may work, but I'm not sure (I need to to understand the article better first)

The main cost of generating a proof is validating/updating the data in the Merkle tree. If we don't have to do that for every block the proof can be generated quicker and cheaper. This of course does not check that the block is actually valid, but using the data published on-chain everybody is able to check if the Merkle tree was correctly updated or not.
- The first proof validates if pretty much everything is correct (request data, signatures) but does not check if the Merkle tree was correctly updated. This proof needs to be put on-chain for each block by the operator just like we currently do (but the proof will be cheaper to generate).
- The second proof that proofs everything is correct (like we do now) only needs to be put on-chain when someone else monitoring the state transitions has detected that it could be wrong (and people are punished/rewarded as needed).

**Comment by dong77** [comment]
I like the direction your proposal leads. Let's call these two types of proofs **light proofs** and **full proofs**. The light proofs can be used to verifies that all leaf nodes (orders, accounts, tokens) have been updated correctly. What it cannot prove, is that the world state's root hash is also corrected updated. 

But do we have to rely on full proofs to verify the root is correctly updated? Can we use Merkle proof alone with the light proof?  We can choose (better randomly) a order node that have been updated in a block, use its latest value to compute a merkle proof, and verify that the root commit is valid. So in verifyBlock, we provide a **light ZKP proof** + such a **merkle proof** to verify a block together.

**Comment by dong77** [comment]
If the idea works, given that the current tree depth is 42 and the account tree depth is 20 (assuming still binary tree), the lightproof generation cost is about 53% compared to the full proof. But for each block, we need to provide a Merkle proof which contains about 38 hashes on-chain, then we do 19 hashing function on-chain to calculate and verify the root.

**Comment by Brechtpd** [comment]
> But do we have to rely on full proofs to verify the root is correctly updated? Can we use Merkle proof alone with the light proof? We can choose (better randomly) a trade-history node that has been updated in a block, use its latest value to compute a Merkle proof, and verify that the root commit is valid. So in verifyBlock, we provide a **light ZKP proof** + such a **Merkle proof** to verify a block together.

I don't think a single Merkle proof (or even several) is enough to verify the transition. A Merkle proof only validates a single leaf! To use a Merkle proof on-chain we would need:
- The leaf value + Merkle proof for the previous Merkle root
- All delta's of the on-chain data availability for this leaf (the same leaf can be updated multiple times) so we can calculate the new leaf state
- Verify the Merkle proof using the newly calculated leaf value with the same Merkle proof against the new Merkle root

And this for all updated leafs! Just checking the a couple of leafs is not good enough because even updating a single leaf incorrectly is disastrous (e.g. change the balance of an account to 100% of tokens in the smart contract) so we cannot afford to not check all leafs. All this work makes it impossible to do on-chain.

All this work is exactly what the circuits do now for updating the Merkle tree. If the method you described could work we could just do in the circuit instead of on-chain because it would be cheaper (Poseidon is expensive on-chain).

I think a possible improvement on this would be to use this for a fraud proof. If someone detects that the Merkle tree was not correctly updated he submits a fraud proof like this for a single leaf that was incorrectly updated. But even for a single leaf this would expensive to calculate because a leaf can be updated >1000x in a block (which will always be the case for large blocks because of operator/protocol fee payments) so I think you'd have to do all the work anyway to not lose any generality.

I currently don't see a way to do this efficiently on-chain/off-chain in a SNARK, but there could of course be another way to do it that I can't think of now.

**Comment by Brechtpd** [comment]
My initial idea certainly doesn't work with only the data we currently post on-chain.

Example: An order is already completely filled, but the the operator lies and says the order was not yet filled (which he can do because the data used in the calculations in the Merkle tree isn't checked). The order can now be filled again, which from the on-chain data's points of view is completely valid because we don't know how much an order can be filled (this data is not available on-chain).

It's hard to split up the work without putting a lot of data on-chain.

**Comment by dong77** [comment]
Closing this issue.
