### ISSUE TITLE
[Protocol3] numAddresses may be artificially decremented to 0

### ISSUE THREAD

**Issue by RobertMCForster** [Loopring/protocols#492]
So I don't think I got this formatting correct and I apologize for that.

In the [withdraw function](https://github.com/Loopring/protocols/blob/b6992c2618f513ffacdd51d04145c999e6323ca3/packages/loopring_v3/contracts/impl/UserStakingPool.sol#L140) of UserStakingPool.sol, a user may repeatedly withdraw 0 tokens without ever having staked any.

This leads to the `numAddresses` variable being able to be artificially decremented to 0. In addition to this making any tracking wildly incorrect, it prohibits any users from withdrawing their full balance. This causes severe pains in the butt for off-chain systems and causes fund loss of 1 wei from each user in the staking pool.

My recommendation for fixing would be to require a user's stake is > 0 on withdraw.

**Comment by Brechtpd** [comment]
Hi again,

I'm pretty sure you're right! And I think your recommendation is good. We need a way to check if the account exists in the first place, none of the existing checks seem to fail if the account doesn't exist.

I'm not that familiar with the staking code myself so I'll let other people look at it as well.

It seems like we're even lucky with the existing code people are still able to withdraw their funds, minus 1 wei :).

**Comment by adamchen0510** [comment]
Hi, RobertMCForster:
Thanks for your info, we already fixed this issue, you can refer to the newest codes.

https://github.com/Loopring/protocols/blob/master/packages/loopring_v3/contracts/impl/UserStakingPool.sol#L110

**Comment by RobertMCForster** [comment]
Ah crap, I guess I spent all that time on the wrong repo haha. So what repo is this bug bounty for exactly if not the one on Gitcoin?

**Comment by dong77** [comment]
@RobertMCForster Thank you for reporting the bug. This finding is eligible for reward :)

**Comment by RobertMCForster** [comment]
@dong77 Awesome, good to hear. Is the repo linked above what I should be hunting though or is that not open to bounty? I see it has some new functionality I'd like to take a look at.

**Comment by dong77** [comment]
If you find some issues, we’ll reward you as well :) Finding issues and fixing them will be rewarded more :)
As of now we don’t know the exact amount though, should be based on the actual contributions.

**Comment by dong77** [comment]
I'm closing this issue.
