### ISSUE TITLE
[Protocol3] Create circuit permutations with fewer fee payments

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#50]
Our current circuits do A LOT of token transfers, which uses a lot of constraints. We may want to create circuit permutations that do not do this many. If needed, Orders/Rings can contain an identifier in which circuit permutation they can be used.

For example, for an Exchange that does everything itself (wallet + ring-matcher + operator) we only need to pay a fee from the order to a single wallet. All payments to the ring-matcher and payment from the ring-matcher to the operator can be removed, greatly increasing the number of constraints used by the circuits (and thus greatly increasing the achievable throughput).

**Comment by dong77** [comment]
@Brechtpd  Given that we simplified fee payment to ring-matcher in #197 , should we close this issue?

**Comment by Brechtpd** [comment]
@dong77 Yes, let's close this one. I think we should still think about how to reduce payments somehow if possible, but not in the way described in this issue.
