### ISSUE TITLE
[Protocol3] Testing SignatureBasedAddressWhitelist

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#514]

**Comment by yueawang** [comment]
Hi, @dong77 
From the code structure, It shows we can have different impl of IAddressWhitelist rather than SignatureBasedAddressWhitelist, any plan about that?
And for test purpose, my understanding is the owner of SignatureBasedAddressWhitelist reads an off-chain whitelist to determine if he signs or not(correct me if I am wrong). Is there any requirement on that off-chain whitelist? like file format, update control, etc.
Thanks!

**Comment by dong77** [comment]
We don’t need to test the interface at all. 

Your understanding is correct regarding the implementation. No need to test the off chain part.

**Comment by yueawang** [comment]
OK, I am creating new cases under the test framework.
Just one thing, Have you met that mismatch issue stated below before? (https://ethereum.stackexchange.com/questions/15364/ecrecover-from-geth-and-web3-eth-sign)

It shows to match the signature between web3 & solidity, we need to modify message string a little bit, i.e. add a specific prefix "\x19Ethereum Signed Message:\n32". I am debugging this, if you met the issue before, maybe I can save some efforts.

**Comment by Brechtpd** [comment]
See here for an example:
- https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/cryptography/ECDSA.sol

You'd use it like this:
```
require(hash.toEthSignedMessageHash().recover(signature) == owner, "UNAUTHORIZED");
```

Probably best to just change the implementation of `SignatureBasedAddressWhitelist` to use the openzeppelin `ECDSA.sol` file directly. That way we can reuse the signature checking code and use code that is already tested. I already used the lib [here](https://github.com/Loopring/protocols/blob/ff689ef183e4ecd50d07bafb9f2fda3cd77d0d5a/packages/loopring_v3/contracts/impl/relayer/FastWithdrawal.sol) for v3.1 for example.

**Comment by yueawang** [comment]
Thanks Brechtpd, I just finished debugging and I think it is ok to upgrade SignatureBasedAddressWhitelist to make use of ECDSA.sol. Maybe in the next PR as this time I did not change SignatureBasedAddressWhitelist.sol so much.

**Comment by dong77** [comment]
Trying to address @Brechtpd 's commet in https://github.com/Loopring/protocols/pull/607/files, but somehow the test fails. I suspect the following code snippet didn't work:

```solidity

    bytes memory sig = new bytes(65);
    for (uint i = 0; i < 65; i++) {
        sig[i] = permission[i + 8];
    }
```
