### ISSUE TITLE
npm install issue?

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#560]
Are you guys seeing this problem when ryun `npm install` in protocol3?
<img width="615" alt="Screen Shot 2019-10-03 at 12 34 08" src="https://user-images.githubusercontent.com/1710087/66146140-2c471d00-e5da-11e9-8f87-6cd0ef42d907.png">

**Comment by Brechtpd** [comment]
Yes, I'm having the same issue, no idea when it started. It seems [other people](https://github.com/nodejs/node-gyp/issues/1906) are having problems as well. I haven't found a way to fix it yet.
