### ISSUE TITLE
[Protocol3] Finalize constants

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#603]
@letsgoustc Please lead the effort to discuss and finalize the constant variables in protocol 3.0. This has to go into beta4. (I assume some tests will fail, so please apply the change to a release branch, not the master).

Some discussion was captured in this doc: https://docs.google.com/spreadsheets/d/1XKOKUtLdh7PZgKWs5HRxK_wrCyt4FbHhRdL4SAW7_Cw/edit#gid=1428741813

**Comment by yueawang** [comment]
#621

**Comment by dong77** [comment]
Done
