### ISSUE TITLE
[Loopring3] Improve code quality based on Audit Report from SECBIT

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#611]
The report is available here: https://github.com/Loopring/protocols/raw/master/packages/loopring_v3/security_audit/LoopringV3_Report_EN.pdf
https://github.com/Loopring/protocols/raw/master/packages/loopring_v3/security_audit/LoopringV3_Report_CN.pdf

**Comment by dong77** [comment]
- 4.3.1 "Definitions and implementations of getLRCFeeStats() interface are inconsistent." ⟶ This has been [fixed](https://github.com/Loopring/protocols/commit/df79c8aab6699aa3adfcbaeaa6e770627de7a40f). 
- 4.3.2 "Assembly code in SignatureBasedAddressWhitelist does not work." ⟶ This has been [fixed](https://github.com/Loopring/protocols/commit/0f7e1951661623b2eae23d7231ea513a822493cf) with additional test cases. 
- 4.3.3 "Operator influence on the choice of maker/taker orders." ⟶ The topic had been [discussed](https://github.com/Loopring/protocols/issues/623): the fact that relayers decide which orders are maker/takers is by design. 
- 4.3.4 "Unchecked return values in use of transferTokens()." ⟶ The transferTokens function is self-checked when allowFailure is false, there is no need to verify the return value by the caller. 
- 4.3.5 "Unclear intention of transferDeposit() function." ⟶ We pass in msg.sender to be more future proof. In future versions, we will allow other addresses to do these kinds of operations for msg.sender (this allows us to support gas station networks, to give just one example of many possible use cases).
- 4.3.6 "Consider about overflow issues of timestamp in Block." ⟶ The current uinty32 type can express timestamp before 2106, and we believe Loopring will surely migrate to new protocols before that deadline. 
- 4.3.7 "TransformRingSettlementDataGadget could be optimized." ⟶The code to shuffle the data availability bits does not have any impact on the performance of the circuits and so was not written for maximum performance, but to make it easy to modify. There is little reason to modify the code at this point, even if you could modify the code to run faster in theory. Data compression inside the circuit (using XOR) is currently disabled, but data compression inside the circuit certainly has its benefits! A balance can be found between what operations are cheap in circuits and what operations are cheap on-chain.
- 4.3.8 "Wrong comment in TakerMakerMatchingGadget." ⟶ This has been resolved by multiple circuit [optimizations](https://github.com/Loopring/protocol3-circuits/commits/master/Gadgets). 
- 4.3.9 "Call logic of generateKeyPair() is impractical." ⟶ This has also been resolved by multiple circuit [optimizations](https://github.com/Loopring/protocol3-circuits/commits/master/Gadgets), and thegenerateKeyPair() method is ONLY called in testing; in production, all proving/verification keys are generated based on the trusted setup MCP ceremony. 
- 4.3.10 "Redundant fields in the OffchainWithdrawalBlock class." ⟶ This has been [fixed](https://github.com/Loopring/protocol3-circuits/commit/77ac4835051cd19d17376e154ad77b27127bfc2a).

**Comment by dong77** [comment]
@Brechtpd can you verify if we can close this issue and release a beta4 version?

**Comment by Brechtpd** [comment]
This issue can be closed. Before making a beta4 release I think we need to merge #690.
