### ISSUE TITLE
[Protocol4] move `blockVerifierAddress` from LoopringV3 to ExchangeV3

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#674]
Currently, we have blockVerifierAddress inside `LoopringV3` and it is updatable by the owner.
I believe a better approach is to bind `blockVerifierAddress` with `ExchangeV3` and make it unchangeable, so using a new `BlockVerifier` requires an explicit new `ExchangeV3` version upgrade. With the new approach, the `BlockVerifier` upgradability becomes explicit, otherwise, a malicious owner can swap to a BlockVerifier that uses a set of malicious circuits in the same version.

We can even improve `BlockVerifier` such that it has a `finalize` method, once called, the contract checks all required keys have been added and becomes ownerless and immutable.

`ExchangeV3` should check its new  `BlockVerifier` has been finalized.

**Comment by Brechtpd** [comment]
> Currently, we have blockVerifierAddress inside `LoopringV3` and it is updatable by the owner.
> I believe a better approach is to bind `blockVerifierAddress` with `ExchangeV3` and make it unchangeable, so using a new `BlockVerifier` requires an explicit new `ExchangeV3` version upgrade. With the new approach, the `BlockVerifier` upgradability becomes explicit, otherwise, a malicious owner can swap to a BlockVerifier that uses a set of malicious circuits in the same version.

`blockVerifierAddress` can be updated in `LoopringV3` (by the owner of `LoopringV3`) but the address is set once in the constructor of `ExchangeV3` so even if it is updated in `LoopringV3` it will not affect existing exchanges, only newly created exchanges. The owner of the exchange cannot set it or change it. Updating the `BlockVerifier` used by the exchange is only possible by doing an upgrade of the exchange with the proxy mechanism.

> We can even improve `BlockVerifier` such that it has a `finalize` method, once called, the contract checks all required keys have been added and becomes ownerless and immutable.
> `ExchangeV3` should check its new `BlockVerifier` has been finalized.

I think you can pretty much anything by implementing the needed logic in the owner contract of `BlockVerifier` (which has its own owner). We can make it immutable by changing the owner to an address that can't do anything of course, but I think it is acceptable (and probably desirable) to keep it mutable with some safety measures (like any change to `BlockVerifier` is applied after at least 1 month for example so users can react, or by letting a DAO make the decisions).

You could link exchange updates and key updates together of course, but I think the current method is also pretty good. And I think what you described can be achieved already with the current method.

**Comment by dong77** [comment]
oh, I didn't notice this:
> blockVerifierAddress can be updated in LoopringV3 (by the owner of LoopringV3) but the address is set once in the constructor of ExchangeV3 so even if it is updated in LoopringV3 it will not affect existing exchanges, only newly created exchanges.
