### ISSUE TITLE
minor code style issue

### ISSUE THREAD

**Issue by p0n1** [Loopring/protocols#684]
https://github.com/Loopring/protocols/blob/c37dc1c58f843a36a91d035c2c27b1482fc5229f/packages/loopring_v3/contracts/impl/UniversalRegistry.sol#L72-L80

The last line

```
 string memory version = ILoopring(protocol).version(); 
```

Why not just as bellow?

```
 string memory version = loopring.version(); 
```

**Comment by dong77** [comment]
Fixed in https://github.com/Loopring/protocols/pull/687. Thank you.
