### ISSUE TITLE
[Protocol3] Groth16 proof forgery

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#729]
We may be vulnerable to this:
- https://medium.com/ppio/how-to-generate-a-groth16-proof-for-forgery-9f857b0dcafd

If we are, we should be able to just use the public data hash as a nullifier. I will look into this more to make sure.

**Comment by Brechtpd** [comment]
I think we're fine because we handle replay protection on the protocol level, and we check the starting Merkle root hash on-chain (which acts as a kind of nullifier in our case). So resubmitting proofs (forged or not) is not an issue.
- For on-chain requests there is never any issue because we check data on-chain
- For off-chain requests it's impossible to commit a block that has the same public input twice because the Merkle tree always changes (the nonces of the accounts always change). This means the Merkle tree always changes, which makes any replay attack with proofs impossible because the public input is always different (the Merkle tree roots (old and new) are part of the public input).

**Comment by adamchen0510** [comment]
Yes.
The author(xin jiang蒋鑫) is one of our colleagues at Marvell.
I've seen his article in Chinese several days ago and discussed with Yue
that forgery proof can't pass in our case.
