### ISSUE TITLE
[tokenbank] implement Kyber and Uniswap based price oracles

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#741]
Please work on top of this PR: https://github.com/Loopring/protocols/pull/740

**Comment by yueawang** [comment]
OK, just one question, the interface is tokenPrice(), what's the unit?? ETH?

**Comment by dong77** [comment]
eth

发自我的iPhone

**Comment by yueawang** [comment]
嗯，对eth价格的api这两个交易所都有。
考虑CNY的话，需要引入更多的Oracle，感觉CNY做在合约内部似乎意义不大。
做了一个简单的实现 https://github.com/Loopring/protocols/pull/757，先看一下，后面再把test补上。
