### ISSUE TITLE
[hebao] Support multiple calls in a single meta-tx

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#784]
Scenario: a user wants to do 10 token transfers. To do these 10 token transfers multiple function calls are needed, each call needs a meta-tx that needs to be signed. If the data can be signed easily for the user this is no problem (though some gas can be saved here as well), but a user may use a hardware wallet, MetaMask or maybe even guardians are needed to sign the transactions because the quota is exceeded.

This could be done on the module level: a function can be created that does batch transfers. But this is just a single use-case and this already needs additional code in the module. It seems like it would be a good idea to make this a standard feature of `MetaTxModule` where it's easy to just make it possible to do multiple function calls inside a single meta-tx so the data needs to be signed only a single time. There is still a limit that the multiple calls need to be done on the same module, but this seems acceptable to me.

**Comment by dong77** [comment]
I would argue that the need to sign multiple meta-transactions in a very small time window should be rare. In the case similar to transferring multiple tokens, a module should provide such a method, as the `transferTokensFullBalance` in `QuotaTransfers`.

**Comment by Brechtpd** [comment]
Perhaps it could be quite rare (depending on how modules are implemented), but it would greatly improve user experience when it's useful. And having the possibility should make modules easier to write.

We already have an `approveThenCallContract` which does 2 single operations in a single function call. `transferTokensFullBalance` does indeed do basically the same as multiple transactions (but limited to full balances). To start trading you currently have to first call `createOrUpdateDEXAccount` and then `depositToDEX` for each token you want to deposit. I think it will allow module functions to be short and easy without having to worry that multiple calls are needed. Why implement methods like this for all different use cases in all modules when you can do it once (easy and simple)?

Personally, I even batch my manual bank payments up because otherwise I have to sign each one individually which really isn't a lot of work but it's tedious to do every time. I would expect people to do the same if the wallet supports it because everybody is lazy. :)

**Comment by dong77** [comment]
@Brechtpd , do you mind creating a PR for this :)
