### ISSUE TITLE
[hebao] Support delegate calls

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#785]
This is something that is done in GnosisSafe which I like. `delegatecall` is supported which can be used to support libraries. The idea is that some extra logic can be done on a call which still executes in the wallet (so `msg.sender` is still the wallet address).

This allows us to do some nice things  which makes things more future proof as well (support new EVM opcodes):
- Allows ue to support more rarely used functions without modifying the wallet. Things like `create` and `create2` may still be useful to be callable by the smart wallet (so the smart wallet is immediately the owner of the created smart contract for example). A module can just let the data in `transact` pass through the library contract that implements this logic.
- Can also be used to do things like #784 by doing the multiple calls logic in a `delegatecall`

**Comment by letsgoustc** [comment]
> This is something that is done in GnosisSafe which I like. `delegatecall` is supported which can be used to support libraries. The idea is that some extra logic can be done on a call which still executes in the wallet (so `msg.sender` is still the wallet address).
> 
> This allows us to do some nice things which makes things more future proof as well (support new EVM opcodes):
> 
> * Allows ue to support more rarely used functions without modifying the wallet. Things like `create` and `create2` may still be useful to be callable by the smart wallet (so the smart wallet is immediately the owner of the created smart contract for example). A module can just let the data in `transact` pass through the library contract that implements this logic.
> * Can also be used to do things like #784 by doing the multiple calls logic in a `delegatecall`

How about we add one more API delegateTransact for Wallet in which we call delegatecall instead of current transact API with call.

**Comment by Brechtpd** [comment]
Yes, I think another external function would work nicely. Internally I would use the same `transactInternal` for normal and delegate calls though because the code can largely be reused (as it's basically the same).

**Comment by dong77** [comment]
Not sure I followed the idea. Are you suggesting when we bind methods, we can give it a type whichi decides whether we should use `staticcalll`, `call`, or `delegatecall` in the default function?

**Comment by Brechtpd** [comment]
It would be mainly for `transact` in the wallet so we can do more logic in the wallet itself without changing `msg.sender` (doing the logic in another contract would change msg.sender for subsequent calls which isn't something we want in some cases). I'll make a PR for this.

**Comment by dong77** [comment]
I see what you mean. So add a `mode` parameter to `transact`? 

```solidity

    enum TransactMode {CALL, DELEGATECALL}
    function transact(
        address to,
        TransactMode mode,
        uint    value,
        bytes   calldata data
        )
        external
        returns (bytes memory result);
```
