### ISSUE TITLE
[hebao] More flexible/accurate gas costs

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#786]
Currently the gas cost charged to the user is `gasSpent + GAS_OVERHEAD`, with `gasSpent` the gas used to execute the meta-tx.

There are some gas costs as well to put all data necessary on-chain for the meta-tx (the `calldata` costs). For example, for protocol V3 committing a block may only use 100,000 gas, but there are a lot of costs to put the data-availability data on-chain. This gas cost isn't part of `gasSpent` because the cost is only charged on the transaction itself.

While we could try to calculate this extra gas cost on-chain by checking the length of all the data passed in, I don't think this really worth it because gas costs may change and other gas costs can still exist (initial 21,000 gas cost/transaction for example).

I think putting the `GAS_OVERHEAD` inside the data signed by the user so it can simply be used on-chain as-is (and the value used calculated off-chain) is a more flexible and easy way to charge these extra gas costs to the user.

**Comment by dong77** [comment]
fixed
