### ISSUE TITLE
[hebao] Enforce the meta-tx nonce to increase by 1

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#787]
The current code allows any nonce that is greater than the last once:
```
require(nonce > wallets[wallet].nonce, "NONCE_TOO_SMALL");
require((nonce >> 128) <= (block.number + BLOCK_BOUND), "NONCE_TOO_LARGE");
wallets[wallet].nonce = nonce;
```

Basically it's the same discussion as done in #635 for the off-chain requests. :)
In this case I would also do the increments by 1, especially because out-of-order requests are also supported when `nonce == 0` by storing the hash.

**Comment by adamchen0510** [comment]
Hi, Brecht:
By this modification, it would be complex for client, especially in debug level.
Client(app we are developing) need get the newest nonce from server(which get from contract, and need also consider for the pending tx) each time before sending a new request,
if previous request failed, the nonce didn't increase in contract(in integration period), the new request sent before previous request executed on chain would be fail as nonce +2 than on chain nonce.

I see the nonce increase by 1 is well known in Ethereum, 
but the previous codes which nonce is bigger than previous but not increase too much is enough, client can fill the timestamp as nonce and don't need consider the nonce any more,  we can save the getNonce each time.

So I think we can choose the easier way that keep previous codes.

**Comment by Brechtpd** [comment]
If the order of the transactions isn't important you can use `nonce = 0` so the hash is used for replay protection. This way the nonce method can still be used when needed to enforce strict ordering of transactions. I agree that an extra `validUntil` timestamp for meta transactions could be useful to limit the time the transaction can be used and to have an easy way to have unique meta transaction with different hashes.

> if previous request failed, the nonce didn't increase in contract(in integration period), the new request sent before previous request executed on chain would be fail as nonce +2 than on chain nonce.

I think this shouldn't really happen (unless there's a bug in the relayer) because the call done in the meta transaction is allowed to fail and the meta transaction will still be marked as executed and the onchain nonce will have increased as expected.

**Comment by adamchen0510** [comment]
> I think this shouldn't really happen (unless there's a bug in the relayer) because the call done in the meta transaction is allowed to fail and the meta transaction will still be marked as executed and the onchain nonce will have increased as expected.
I mean the debug period, if return by INVALID_SIGNATURES. I said this just to say it's not convenience for developing,  if use previous codes this would not happen.

> I agree that an extra validUntil timestamp for meta transactions could be useful to limit the time the transaction can be used and to have an easy way to have unique meta transaction with different hashes.
What's the validUntil come from? 

```
require(nonce > wallets[wallet].nonce, "NONCE_TOO_SMALL");
require((nonce >> 128) <= (block.number + BLOCK_BOUND), "NONCE_TOO_LARGE");
wallets[wallet].nonce = nonce;
```
For these codes, I think it's security enough for replay attack and friendly for client, don't need use nonce = previous_nonce + 1

**Comment by Brechtpd** [comment]
> What's the validUntil come from? you mean add a validUntil timestamp in metaTransation? yes, if so, it would resolve my question too.

Yeah, just an extra field in `MetaTransaction`.

> For these codes, I think it's security enough for replay attack and friendly for client, don't need use nonce = previous_nonce + 1

Even with the more lenient code the relayer needs to keep track of the nonce for each user because the transactions still need to be executed in the same `nonce = previous_nonce + 1`. If there are transactions with `nonce = 8` and `nonce = 9` the relayer still needs to do the transaction with `nonce = 8` first and then the transaction with  `nonce = 9`, otherwise the user would have to re-sign the transaction with `nonce = 8` with e.g. `nonce = 10`. So for the actual client implementation I think it doesn't matter much which method is actually used (and enforcing `nonce = previous_nonce + 1` has some benefits).

If you think this is still a big problem than I'm okay with the other code, I'm just not sure it really makes anything easier. I think only the `nonce = 0` method allows the client to not do any nonce tracking.

**Comment by adamchen0510** [comment]
> If you think this is still a big problem than I'm okay with the other code, I'm just not sure it really makes anything easier. I think only the nonce = 0 method allows the client to not do any nonce tracking.

 Now client can not do much thing when nonce=0, client need save previous gasLimit or gasPrice(it's just hack to generate different hash) to avoid generate same hash. If add a `validUntil` that much more easier(need to see if need now).

I think more lenient code is more easier than increase by 1 now. We'll revert the patch to test:), thanks!
