### ISSUE TITLE
[Loopring v4] Managing Dependencies using a dedicated contract

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#900]
We should use an owned dedicated contract to manage Loopring/Exchange's dependencies. Currently, these dependencies are managed by ILoopring30 or IExchange30.

A related small issue is that it's hard to find out the BlockVerifier address used by Loopring30.

**Comment by Brechtpd** [comment]
In certain scenario's it may make sense to not share the dependencies (e.g. #674). Though some of the concerns could probably be solved differently with a shared state. Is there currently any dependency other than `blockVerifier` that could be shared?

**Comment by dong77** [comment]
I don't have another example on top of my head. The reason to have this issue created is that I like the [Controller](https://github.com/Loopring/protocols/blob/master/packages/hebao_v1/contracts/iface/Controller.sol) design in Hebao's contract.

A more important question is how we can better modulize the Exchange's contract design, so future implementation will be easier.

One goal I have is to enable different block types to manage their on-chain data independently. Currently, they are very tightly coupled.
