### ISSUE TITLE
[Loopring v4] Keep track of a moving average of time difference

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#902]
I propose that we keep track of the difference between the time used by the operator and the block time, and punish the operator (by burning LRC) based on a (100-block) moving average instead of the time difference for a certain block.

**Comment by Brechtpd** [comment]
I'm not sure this is a good idea.
- The moving average would be based on the way the operator chooses the timestamp so he could manipulate this himself, so the difference could be very large. To solve this we would need to have a hard cap like we do know.
- The time difference also depends on when the operator gets his transaction included in a block which is out of his control (the operator could pay a higher gas than really needed to minimize the risk, but there could still be short periods of congestion that are hard to predict).
- If there's a fixed time period users could even take this in mind when creating an order by setting the `validUntil` time to `expectedValidUntil - delta` (though I don't think any exchange will even try to abuse this time delta).
- Storing the data necessary for calculating the moving average could increase the gas costs for submitting a block, which may not be worth it for things like this.

**Comment by dong77** [comment]
After a second thought, I think I agree not to implement something like this.
