### ISSUE TITLE
[Loopring v4] expose more cheap stats

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#905]
I think we can add more stats to the IExchange31 interface if the extra costs are very small:

A preliminary list:
- numOfXxxBlocks
- numOfXxxBlocksSubmitted
- numOfDeposits
- numOfDepositsSubmitted
- numOfWithdrawals
- numOfWithdrawalsSubmitted
- numOfWithdrawalsDistributed
- numOfTrades

Current the operator address is not exposed by ABI, which is not good.

**Comment by Brechtpd** [comment]
The cost for storing this data will always be significant (though this data could be packed somewhat to have fewer SSTORES, it will still be quite costly at 5000 gas/SSTORE). I also don't see these stats being particularly useful on-chain by other smart contracts, and the DEX browser can have much better stats than we can have on-chain (detecting padding in off-chain block types, etc...). So if you want these stats you would go to the DEX browser anyway. 

> Current the operator address is not exposed by ABI, which is not good.

It would have been better if it would be exposed as there is no reason not to expose it, though I don't think this is that bad, it's not like this is really important to know on-chain externally. And off-chain
- You can easily find it by searching the `OperatorChanged` events (which you can even do on etherscan).
- Data like this will be available in the DEX browser which will be the entry point for people to see data about the exchanges.

**Comment by dong77** [comment]
It seems we should embrace the following principles:
- As few on-chain stats as possible to reduce gas cost
- Expose as many public data as possible if they are already on-chain.
