### ISSUE TITLE
[Loopring v4] encode `uint8 blockType`, `uint16 blockSize`, `uint8 blockVersion` as bytes64

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#911]
I'm not sure this will save gas though :) Do you know, @Brechtpd ?

**Comment by Brechtpd** [comment]
It could save maybe 300 gas or something, not that significant.

I think for the next release with solidity 0.6 I think we can start using enums and structs in our interfaces where it makes sense to make them cleaner. Making the interface harder to use with manual packing/unpacking of data is I think unnecessary compared to the possible gas savings.

**Comment by dong77** [comment]
Agreed. We may want to optimize hebao’s contract to learn more about solidity 0.6
